/* This file is automatically generated by generator.prg originated from
   https://github.com/alcz/harbour-cimgui-sokol-starterkit
   based on output/definitions.json from cimgui https://github.com/cimgui/cimgui which is
   based on imgui.h file version "1.86" from Dear ImGui https://github.com/ocornut/imgui */

#xtranslate ImGui:: => ig

#define ImDrawFlags_None                                                0 /* 0 */
#define ImDrawFlags_Closed                                              1 /* 1 << 0 */
#define ImDrawFlags_RoundCornersTopLeft                                16 /* 1 << 4 */
#define ImDrawFlags_RoundCornersTopRight                               32 /* 1 << 5 */
#define ImDrawFlags_RoundCornersBottomLeft                             64 /* 1 << 6 */
#define ImDrawFlags_RoundCornersBottomRight                           128 /* 1 << 7 */
#define ImDrawFlags_RoundCornersNone                                  256 /* 1 << 8 */
#define ImDrawFlags_RoundCornersTop                                    48 /* ImDrawFlags_RoundCornersTopLeft | ImDrawFlags_RoundCornersTopRight */
#define ImDrawFlags_RoundCornersBottom                                192 /* ImDrawFlags_RoundCornersBottomLeft | ImDrawFlags_RoundCornersBottomRight */
#define ImDrawFlags_RoundCornersLeft                                   80 /* ImDrawFlags_RoundCornersBottomLeft | ImDrawFlags_RoundCornersTopLeft */
#define ImDrawFlags_RoundCornersRight                                 160 /* ImDrawFlags_RoundCornersBottomRight | ImDrawFlags_RoundCornersTopRight */
#define ImDrawFlags_RoundCornersAll                                   240 /* ImDrawFlags_RoundCornersTopLeft | ImDrawFlags_RoundCornersTopRight | ImDrawFlags_RoundCornersBottomLeft | ImDrawFlags_RoundCornersBottomRight */
#define ImDrawFlags_RoundCornersDefault_                              240 /* ImDrawFlags_RoundCornersAll */
#define ImDrawFlags_RoundCornersMask_                                 496 /* ImDrawFlags_RoundCornersAll | ImDrawFlags_RoundCornersNone */
#define ImDrawListFlags_None                                            0 /* 0 */
#define ImDrawListFlags_AntiAliasedLines                                1 /* 1 << 0 */
#define ImDrawListFlags_AntiAliasedLinesUseTex                          2 /* 1 << 1 */
#define ImDrawListFlags_AntiAliasedFill                                 4 /* 1 << 2 */
#define ImDrawListFlags_AllowVtxOffset                                  8 /* 1 << 3 */
#define ImFontAtlasFlags_None                                           0 /* 0 */
#define ImFontAtlasFlags_NoPowerOfTwoHeight                             1 /* 1 << 0 */
#define ImFontAtlasFlags_NoMouseCursors                                 2 /* 1 << 1 */
#define ImFontAtlasFlags_NoBakedLines                                   4 /* 1 << 2 */
#define ImGuiActivateFlags_None                                         0 /* 0 */
#define ImGuiActivateFlags_PreferInput                                  1 /* 1 << 0 */
#define ImGuiActivateFlags_PreferTweak                                  2 /* 1 << 1 */
#define ImGuiActivateFlags_TryToPreserveState                           4 /* 1 << 2 */
#define ImGuiAxis_None                                                 -1 /* -1 */
#define ImGuiAxis_X                                                     0 /* 0 */
#define ImGuiAxis_Y                                                     1 /* 1 */
#define ImGuiBackendFlags_None                                          0 /* 0 */
#define ImGuiBackendFlags_HasGamepad                                    1 /* 1 << 0 */
#define ImGuiBackendFlags_HasMouseCursors                               2 /* 1 << 1 */
#define ImGuiBackendFlags_HasSetMousePos                                4 /* 1 << 2 */
#define ImGuiBackendFlags_RendererHasVtxOffset                          8 /* 1 << 3 */
#define ImGuiBackendFlags_PlatformHasViewports                       1024 /* 1 << 10 */
#define ImGuiBackendFlags_HasMouseHoveredViewport                    2048 /* 1 << 11 */
#define ImGuiBackendFlags_RendererHasViewports                       4096 /* 1 << 12 */
#define ImGuiButtonFlags_PressedOnClick                                16 /* 1 << 4 */
#define ImGuiButtonFlags_PressedOnClickRelease                         32 /* 1 << 5 */
#define ImGuiButtonFlags_PressedOnClickReleaseAnywhere                 64 /* 1 << 6 */
#define ImGuiButtonFlags_PressedOnRelease                             128 /* 1 << 7 */
#define ImGuiButtonFlags_PressedOnDoubleClick                         256 /* 1 << 8 */
#define ImGuiButtonFlags_PressedOnDragDropHold                        512 /* 1 << 9 */
#define ImGuiButtonFlags_Repeat                                      1024 /* 1 << 10 */
#define ImGuiButtonFlags_FlattenChildren                             2048 /* 1 << 11 */
#define ImGuiButtonFlags_AllowItemOverlap                            4096 /* 1 << 12 */
#define ImGuiButtonFlags_DontClosePopups                             8192 /* 1 << 13 */
#define ImGuiButtonFlags_AlignTextBaseLine                          32768 /* 1 << 15 */
#define ImGuiButtonFlags_NoKeyModifiers                             65536 /* 1 << 16 */
#define ImGuiButtonFlags_NoHoldingActiveId                         131072 /* 1 << 17 */
#define ImGuiButtonFlags_NoNavFocus                                262144 /* 1 << 18 */
#define ImGuiButtonFlags_NoHoveredOnFocus                          524288 /* 1 << 19 */
#define ImGuiButtonFlags_PressedOnMask_                              1008 /* ImGuiButtonFlags_PressedOnClick | ImGuiButtonFlags_PressedOnClickRelease | ImGuiButtonFlags_PressedOnClickReleaseAnywhere | ImGuiButtonFlags_PressedOnRelease | ImGuiButtonFlags_PressedOnDoubleClick | ImGuiButtonFlags_PressedOnDragDropHold */
#define ImGuiButtonFlags_PressedOnDefault_                             32 /* ImGuiButtonFlags_PressedOnClickRelease */
#define ImGuiButtonFlags_None                                           0 /* 0 */
#define ImGuiButtonFlags_MouseButtonLeft                                1 /* 1 << 0 */
#define ImGuiButtonFlags_MouseButtonRight                               2 /* 1 << 1 */
#define ImGuiButtonFlags_MouseButtonMiddle                              4 /* 1 << 2 */
#define ImGuiButtonFlags_MouseButtonMask_                               7 /* ImGuiButtonFlags_MouseButtonLeft | ImGuiButtonFlags_MouseButtonRight | ImGuiButtonFlags_MouseButtonMiddle */
#define ImGuiButtonFlags_MouseButtonDefault_                            1 /* ImGuiButtonFlags_MouseButtonLeft */
#define ImGuiCol_Text                                                   0 /* 0 */
#define ImGuiCol_TextDisabled                                           1 /* 1 */
#define ImGuiCol_WindowBg                                               2 /* 2 */
#define ImGuiCol_ChildBg                                                3 /* 3 */
#define ImGuiCol_PopupBg                                                4 /* 4 */
#define ImGuiCol_Border                                                 5 /* 5 */
#define ImGuiCol_BorderShadow                                           6 /* 6 */
#define ImGuiCol_FrameBg                                                7 /* 7 */
#define ImGuiCol_FrameBgHovered                                         8 /* 8 */
#define ImGuiCol_FrameBgActive                                          9 /* 9 */
#define ImGuiCol_TitleBg                                               10 /* 10 */
#define ImGuiCol_TitleBgActive                                         11 /* 11 */
#define ImGuiCol_TitleBgCollapsed                                      12 /* 12 */
#define ImGuiCol_MenuBarBg                                             13 /* 13 */
#define ImGuiCol_ScrollbarBg                                           14 /* 14 */
#define ImGuiCol_ScrollbarGrab                                         15 /* 15 */
#define ImGuiCol_ScrollbarGrabHovered                                  16 /* 16 */
#define ImGuiCol_ScrollbarGrabActive                                   17 /* 17 */
#define ImGuiCol_CheckMark                                             18 /* 18 */
#define ImGuiCol_SliderGrab                                            19 /* 19 */
#define ImGuiCol_SliderGrabActive                                      20 /* 20 */
#define ImGuiCol_Button                                                21 /* 21 */
#define ImGuiCol_ButtonHovered                                         22 /* 22 */
#define ImGuiCol_ButtonActive                                          23 /* 23 */
#define ImGuiCol_Header                                                24 /* 24 */
#define ImGuiCol_HeaderHovered                                         25 /* 25 */
#define ImGuiCol_HeaderActive                                          26 /* 26 */
#define ImGuiCol_Separator                                             27 /* 27 */
#define ImGuiCol_SeparatorHovered                                      28 /* 28 */
#define ImGuiCol_SeparatorActive                                       29 /* 29 */
#define ImGuiCol_ResizeGrip                                            30 /* 30 */
#define ImGuiCol_ResizeGripHovered                                     31 /* 31 */
#define ImGuiCol_ResizeGripActive                                      32 /* 32 */
#define ImGuiCol_Tab                                                   33 /* 33 */
#define ImGuiCol_TabHovered                                            34 /* 34 */
#define ImGuiCol_TabActive                                             35 /* 35 */
#define ImGuiCol_TabUnfocused                                          36 /* 36 */
#define ImGuiCol_TabUnfocusedActive                                    37 /* 37 */
#define ImGuiCol_DockingPreview                                        38 /* 38 */
#define ImGuiCol_DockingEmptyBg                                        39 /* 39 */
#define ImGuiCol_PlotLines                                             40 /* 40 */
#define ImGuiCol_PlotLinesHovered                                      41 /* 41 */
#define ImGuiCol_PlotHistogram                                         42 /* 42 */
#define ImGuiCol_PlotHistogramHovered                                  43 /* 43 */
#define ImGuiCol_TableHeaderBg                                         44 /* 44 */
#define ImGuiCol_TableBorderStrong                                     45 /* 45 */
#define ImGuiCol_TableBorderLight                                      46 /* 46 */
#define ImGuiCol_TableRowBg                                            47 /* 47 */
#define ImGuiCol_TableRowBgAlt                                         48 /* 48 */
#define ImGuiCol_TextSelectedBg                                        49 /* 49 */
#define ImGuiCol_DragDropTarget                                        50 /* 50 */
#define ImGuiCol_NavHighlight                                          51 /* 51 */
#define ImGuiCol_NavWindowingHighlight                                 52 /* 52 */
#define ImGuiCol_NavWindowingDimBg                                     53 /* 53 */
#define ImGuiCol_ModalWindowDimBg                                      54 /* 54 */
#define ImGuiCol_COUNT                                                 55 /* 55 */
#define ImGuiColorEditFlags_None                                        0 /* 0 */
#define ImGuiColorEditFlags_NoAlpha                                     2 /* 1 << 1 */
#define ImGuiColorEditFlags_NoPicker                                    4 /* 1 << 2 */
#define ImGuiColorEditFlags_NoOptions                                   8 /* 1 << 3 */
#define ImGuiColorEditFlags_NoSmallPreview                             16 /* 1 << 4 */
#define ImGuiColorEditFlags_NoInputs                                   32 /* 1 << 5 */
#define ImGuiColorEditFlags_NoTooltip                                  64 /* 1 << 6 */
#define ImGuiColorEditFlags_NoLabel                                   128 /* 1 << 7 */
#define ImGuiColorEditFlags_NoSidePreview                             256 /* 1 << 8 */
#define ImGuiColorEditFlags_NoDragDrop                                512 /* 1 << 9 */
#define ImGuiColorEditFlags_NoBorder                                 1024 /* 1 << 10 */
#define ImGuiColorEditFlags_AlphaBar                                65536 /* 1 << 16 */
#define ImGuiColorEditFlags_AlphaPreview                           131072 /* 1 << 17 */
#define ImGuiColorEditFlags_AlphaPreviewHalf                       262144 /* 1 << 18 */
#define ImGuiColorEditFlags_HDR                                    524288 /* 1 << 19 */
#define ImGuiColorEditFlags_DisplayRGB                            1048576 /* 1 << 20 */
#define ImGuiColorEditFlags_DisplayHSV                            2097152 /* 1 << 21 */
#define ImGuiColorEditFlags_DisplayHex                            4194304 /* 1 << 22 */
#define ImGuiColorEditFlags_Uint8                                 8388608 /* 1 << 23 */
#define ImGuiColorEditFlags_Float                                16777216 /* 1 << 24 */
#define ImGuiColorEditFlags_PickerHueBar                         33554432 /* 1 << 25 */
#define ImGuiColorEditFlags_PickerHueWheel                       67108864 /* 1 << 26 */
#define ImGuiColorEditFlags_InputRGB                            134217728 /* 1 << 27 */
#define ImGuiColorEditFlags_InputHSV                            268435456 /* 1 << 28 */
#define ImGuiColorEditFlags_DefaultOptions_                     177209344 /* ImGuiColorEditFlags_Uint8 | ImGuiColorEditFlags_DisplayRGB | ImGuiColorEditFlags_InputRGB | ImGuiColorEditFlags_PickerHueBar */
#define ImGuiColorEditFlags_DisplayMask_                          7340032 /* ImGuiColorEditFlags_DisplayRGB | ImGuiColorEditFlags_DisplayHSV | ImGuiColorEditFlags_DisplayHex */
#define ImGuiColorEditFlags_DataTypeMask_                        25165824 /* ImGuiColorEditFlags_Uint8 | ImGuiColorEditFlags_Float */
#define ImGuiColorEditFlags_PickerMask_                         100663296 /* ImGuiColorEditFlags_PickerHueWheel | ImGuiColorEditFlags_PickerHueBar */
#define ImGuiColorEditFlags_InputMask_                          402653184 /* ImGuiColorEditFlags_InputRGB | ImGuiColorEditFlags_InputHSV */
#define ImGuiComboFlags_CustomPreview                             1048576 /* 1 << 20 */
#define ImGuiComboFlags_None                                            0 /* 0 */
#define ImGuiComboFlags_PopupAlignLeft                                  1 /* 1 << 0 */
#define ImGuiComboFlags_HeightSmall                                     2 /* 1 << 1 */
#define ImGuiComboFlags_HeightRegular                                   4 /* 1 << 2 */
#define ImGuiComboFlags_HeightLarge                                     8 /* 1 << 3 */
#define ImGuiComboFlags_HeightLargest                                  16 /* 1 << 4 */
#define ImGuiComboFlags_NoArrowButton                                  32 /* 1 << 5 */
#define ImGuiComboFlags_NoPreview                                      64 /* 1 << 6 */
#define ImGuiComboFlags_HeightMask_                                    30 /* ImGuiComboFlags_HeightSmall | ImGuiComboFlags_HeightRegular | ImGuiComboFlags_HeightLarge | ImGuiComboFlags_HeightLargest */
#define ImGuiCond_None                                                  0 /* 0 */
#define ImGuiCond_Always                                                1 /* 1 << 0 */
#define ImGuiCond_Once                                                  2 /* 1 << 1 */
#define ImGuiCond_FirstUseEver                                          4 /* 1 << 2 */
#define ImGuiCond_Appearing                                             8 /* 1 << 3 */
#define ImGuiConfigFlags_None                                           0 /* 0 */
#define ImGuiConfigFlags_NavEnableKeyboard                              1 /* 1 << 0 */
#define ImGuiConfigFlags_NavEnableGamepad                               2 /* 1 << 1 */
#define ImGuiConfigFlags_NavEnableSetMousePos                           4 /* 1 << 2 */
#define ImGuiConfigFlags_NavNoCaptureKeyboard                           8 /* 1 << 3 */
#define ImGuiConfigFlags_NoMouse                                       16 /* 1 << 4 */
#define ImGuiConfigFlags_NoMouseCursorChange                           32 /* 1 << 5 */
#define ImGuiConfigFlags_DockingEnable                                 64 /* 1 << 6 */
#define ImGuiConfigFlags_ViewportsEnable                             1024 /* 1 << 10 */
#define ImGuiConfigFlags_DpiEnableScaleViewports                    16384 /* 1 << 14 */
#define ImGuiConfigFlags_DpiEnableScaleFonts                        32768 /* 1 << 15 */
#define ImGuiConfigFlags_IsSRGB                                   1048576 /* 1 << 20 */
#define ImGuiConfigFlags_IsTouchScreen                            2097152 /* 1 << 21 */
#define ImGuiContextHookType_NewFramePre                                0 /* 0 */
#define ImGuiContextHookType_NewFramePost                               1 /* 1 */
#define ImGuiContextHookType_EndFramePre                                2 /* 2 */
#define ImGuiContextHookType_EndFramePost                               3 /* 3 */
#define ImGuiContextHookType_RenderPre                                  4 /* 4 */
#define ImGuiContextHookType_RenderPost                                 5 /* 5 */
#define ImGuiContextHookType_Shutdown                                   6 /* 6 */
#define ImGuiContextHookType_PendingRemoval_                            7 /* 7 */
#define ImGuiDataAuthority_Auto                                         0 /* 0 */
#define ImGuiDataAuthority_DockNode                                     1 /* 1 */
#define ImGuiDataAuthority_Window                                       2 /* 2 */
#define ImGuiDataType_String                                           11 /* ImGuiDataType_COUNT + 1 */
#define ImGuiDataType_Pointer                                          12 /* ImGuiDataType_COUNT + 1+1 */
#define ImGuiDataType_ID                                               13 /* ImGuiDataType_COUNT + 1+1+1 */
#define ImGuiDataType_S8                                                0 /* 0 */
#define ImGuiDataType_U8                                                1 /* 1 */
#define ImGuiDataType_S16                                               2 /* 2 */
#define ImGuiDataType_U16                                               3 /* 3 */
#define ImGuiDataType_S32                                               4 /* 4 */
#define ImGuiDataType_U32                                               5 /* 5 */
#define ImGuiDataType_S64                                               6 /* 6 */
#define ImGuiDataType_U64                                               7 /* 7 */
#define ImGuiDataType_Float                                             8 /* 8 */
#define ImGuiDataType_Double                                            9 /* 9 */
#define ImGuiDataType_COUNT                                            10 /* 10 */
#define ImGuiDir_None                                                  -1 /* -1 */
#define ImGuiDir_Left                                                   0 /* 0 */
#define ImGuiDir_Right                                                  1 /* 1 */
#define ImGuiDir_Up                                                     2 /* 2 */
#define ImGuiDir_Down                                                   3 /* 3 */
#define ImGuiDir_COUNT                                                  4 /* 4 */
#define ImGuiDockNodeFlags_DockSpace                                 1024 /* 1 << 10 */
#define ImGuiDockNodeFlags_CentralNode                               2048 /* 1 << 11 */
#define ImGuiDockNodeFlags_NoTabBar                                  4096 /* 1 << 12 */
#define ImGuiDockNodeFlags_HiddenTabBar                              8192 /* 1 << 13 */
#define ImGuiDockNodeFlags_NoWindowMenuButton                       16384 /* 1 << 14 */
#define ImGuiDockNodeFlags_NoCloseButton                            32768 /* 1 << 15 */
#define ImGuiDockNodeFlags_NoDocking                                65536 /* 1 << 16 */
#define ImGuiDockNodeFlags_NoDockingSplitMe                        131072 /* 1 << 17 */
#define ImGuiDockNodeFlags_NoDockingSplitOther                     262144 /* 1 << 18 */
#define ImGuiDockNodeFlags_NoDockingOverMe                         524288 /* 1 << 19 */
#define ImGuiDockNodeFlags_NoDockingOverOther                     1048576 /* 1 << 20 */
#define ImGuiDockNodeFlags_NoDockingOverEmpty                     2097152 /* 1 << 21 */
#define ImGuiDockNodeFlags_NoResizeX                              4194304 /* 1 << 22 */
#define ImGuiDockNodeFlags_NoResizeY                              8388608 /* 1 << 23 */
#define ImGuiDockNodeFlags_SharedFlagsInheritMask_                     -1 /* ~0 */
#define ImGuiDockNodeFlags_NoResizeFlagsMask_                    12582944 /* ImGuiDockNodeFlags_NoResize | ImGuiDockNodeFlags_NoResizeX | ImGuiDockNodeFlags_NoResizeY */
#define ImGuiDockNodeFlags_LocalFlagsMask_                       12713072 /* ImGuiDockNodeFlags_NoSplit | ImGuiDockNodeFlags_NoResizeFlagsMask_ | ImGuiDockNodeFlags_AutoHideTabBar | ImGuiDockNodeFlags_DockSpace | ImGuiDockNodeFlags_CentralNode | ImGuiDockNodeFlags_NoTabBar | ImGuiDockNodeFlags_HiddenTabBar | ImGuiDockNodeFlags_NoWindowMenuButton | ImGuiDockNodeFlags_NoCloseButton | ImGuiDockNodeFlags_NoDocking */
#define ImGuiDockNodeFlags_LocalFlagsTransferMask_               12712048 /* ImGuiDockNodeFlags_LocalFlagsMask_ & ~ImGuiDockNodeFlags_DockSpace */
#define ImGuiDockNodeFlags_SavedFlagsMask_                       12712992 /* ImGuiDockNodeFlags_NoResizeFlagsMask_ | ImGuiDockNodeFlags_DockSpace | ImGuiDockNodeFlags_CentralNode | ImGuiDockNodeFlags_NoTabBar | ImGuiDockNodeFlags_HiddenTabBar | ImGuiDockNodeFlags_NoWindowMenuButton | ImGuiDockNodeFlags_NoCloseButton | ImGuiDockNodeFlags_NoDocking */
#define ImGuiDockNodeFlags_None                                         0 /* 0 */
#define ImGuiDockNodeFlags_KeepAliveOnly                                1 /* 1 << 0 */
#define ImGuiDockNodeFlags_NoDockingInCentralNode                       4 /* 1 << 2 */
#define ImGuiDockNodeFlags_PassthruCentralNode                          8 /* 1 << 3 */
#define ImGuiDockNodeFlags_NoSplit                                     16 /* 1 << 4 */
#define ImGuiDockNodeFlags_NoResize                                    32 /* 1 << 5 */
#define ImGuiDockNodeFlags_AutoHideTabBar                              64 /* 1 << 6 */
#define ImGuiDockNodeState_Unknown                                      0 /* 0 */
#define ImGuiDockNodeState_HostWindowHiddenBecauseSingleWindow          1 /* 1 */
#define ImGuiDockNodeState_HostWindowHiddenBecauseWindowsAreResizing         2 /* 2 */
#define ImGuiDockNodeState_HostWindowVisible                            3 /* 3 */
#define ImGuiDragDropFlags_None                                         0 /* 0 */
#define ImGuiDragDropFlags_SourceNoPreviewTooltip                       1 /* 1 << 0 */
#define ImGuiDragDropFlags_SourceNoDisableHover                         2 /* 1 << 1 */
#define ImGuiDragDropFlags_SourceNoHoldToOpenOthers                     4 /* 1 << 2 */
#define ImGuiDragDropFlags_SourceAllowNullID                            8 /* 1 << 3 */
#define ImGuiDragDropFlags_SourceExtern                                16 /* 1 << 4 */
#define ImGuiDragDropFlags_SourceAutoExpirePayload                     32 /* 1 << 5 */
#define ImGuiDragDropFlags_AcceptBeforeDelivery                      1024 /* 1 << 10 */
#define ImGuiDragDropFlags_AcceptNoDrawDefaultRect                   2048 /* 1 << 11 */
#define ImGuiDragDropFlags_AcceptNoPreviewTooltip                    4096 /* 1 << 12 */
#define ImGuiDragDropFlags_AcceptPeekOnly                            3072 /* ImGuiDragDropFlags_AcceptBeforeDelivery | ImGuiDragDropFlags_AcceptNoDrawDefaultRect */
#define ImGuiFocusedFlags_None                                          0 /* 0 */
#define ImGuiFocusedFlags_ChildWindows                                  1 /* 1 << 0 */
#define ImGuiFocusedFlags_RootWindow                                    2 /* 1 << 1 */
#define ImGuiFocusedFlags_AnyWindow                                     4 /* 1 << 2 */
#define ImGuiFocusedFlags_NoPopupHierarchy                              8 /* 1 << 3 */
#define ImGuiFocusedFlags_DockHierarchy                                16 /* 1 << 4 */
#define ImGuiFocusedFlags_RootAndChildWindows                           3 /* ImGuiFocusedFlags_RootWindow | ImGuiFocusedFlags_ChildWindows */
#define ImGuiHoveredFlags_None                                          0 /* 0 */
#define ImGuiHoveredFlags_ChildWindows                                  1 /* 1 << 0 */
#define ImGuiHoveredFlags_RootWindow                                    2 /* 1 << 1 */
#define ImGuiHoveredFlags_AnyWindow                                     4 /* 1 << 2 */
#define ImGuiHoveredFlags_NoPopupHierarchy                              8 /* 1 << 3 */
#define ImGuiHoveredFlags_DockHierarchy                                16 /* 1 << 4 */
#define ImGuiHoveredFlags_AllowWhenBlockedByPopup                      32 /* 1 << 5 */
#define ImGuiHoveredFlags_AllowWhenBlockedByActiveItem                128 /* 1 << 7 */
#define ImGuiHoveredFlags_AllowWhenOverlapped                         256 /* 1 << 8 */
#define ImGuiHoveredFlags_AllowWhenDisabled                           512 /* 1 << 9 */
#define ImGuiHoveredFlags_RectOnly                                    416 /* ImGuiHoveredFlags_AllowWhenBlockedByPopup | ImGuiHoveredFlags_AllowWhenBlockedByActiveItem | ImGuiHoveredFlags_AllowWhenOverlapped */
#define ImGuiHoveredFlags_RootAndChildWindows                           3 /* ImGuiHoveredFlags_RootWindow | ImGuiHoveredFlags_ChildWindows */
#define ImGuiInputReadMode_Down                                         0 /* 0 */
#define ImGuiInputReadMode_Pressed                                      1 /* 1 */
#define ImGuiInputReadMode_Released                                     2 /* 2 */
#define ImGuiInputReadMode_Repeat                                       3 /* 3 */
#define ImGuiInputReadMode_RepeatSlow                                   4 /* 4 */
#define ImGuiInputReadMode_RepeatFast                                   5 /* 5 */
#define ImGuiInputSource_None                                           0 /* 0 */
#define ImGuiInputSource_Mouse                                          1 /* 1 */
#define ImGuiInputSource_Keyboard                                       2 /* 2 */
#define ImGuiInputSource_Gamepad                                        3 /* 3 */
#define ImGuiInputSource_Nav                                            4 /* 4 */
#define ImGuiInputSource_Clipboard                                      5 /* 5 */
#define ImGuiInputSource_COUNT                                          6 /* 6 */
#define ImGuiInputTextFlags_Multiline                            67108864 /* 1 << 26 */
#define ImGuiInputTextFlags_NoMarkEdited                        134217728 /* 1 << 27 */
#define ImGuiInputTextFlags_MergedItem                          268435456 /* 1 << 28 */
#define ImGuiInputTextFlags_None                                        0 /* 0 */
#define ImGuiInputTextFlags_CharsDecimal                                1 /* 1 << 0 */
#define ImGuiInputTextFlags_CharsHexadecimal                            2 /* 1 << 1 */
#define ImGuiInputTextFlags_CharsUppercase                              4 /* 1 << 2 */
#define ImGuiInputTextFlags_CharsNoBlank                                8 /* 1 << 3 */
#define ImGuiInputTextFlags_AutoSelectAll                              16 /* 1 << 4 */
#define ImGuiInputTextFlags_EnterReturnsTrue                           32 /* 1 << 5 */
#define ImGuiInputTextFlags_CallbackCompletion                         64 /* 1 << 6 */
#define ImGuiInputTextFlags_CallbackHistory                           128 /* 1 << 7 */
#define ImGuiInputTextFlags_CallbackAlways                            256 /* 1 << 8 */
#define ImGuiInputTextFlags_CallbackCharFilter                        512 /* 1 << 9 */
#define ImGuiInputTextFlags_AllowTabInput                            1024 /* 1 << 10 */
#define ImGuiInputTextFlags_CtrlEnterForNewLine                      2048 /* 1 << 11 */
#define ImGuiInputTextFlags_NoHorizontalScroll                       4096 /* 1 << 12 */
#define ImGuiInputTextFlags_AlwaysOverwrite                          8192 /* 1 << 13 */
#define ImGuiInputTextFlags_ReadOnly                                16384 /* 1 << 14 */
#define ImGuiInputTextFlags_Password                                32768 /* 1 << 15 */
#define ImGuiInputTextFlags_NoUndoRedo                              65536 /* 1 << 16 */
#define ImGuiInputTextFlags_CharsScientific                        131072 /* 1 << 17 */
#define ImGuiInputTextFlags_CallbackResize                         262144 /* 1 << 18 */
#define ImGuiInputTextFlags_CallbackEdit                           524288 /* 1 << 19 */
#define ImGuiItemFlags_None                                             0 /* 0 */
#define ImGuiItemFlags_NoTabStop                                        1 /* 1 << 0 */
#define ImGuiItemFlags_ButtonRepeat                                     2 /* 1 << 1 */
#define ImGuiItemFlags_Disabled                                         4 /* 1 << 2 */
#define ImGuiItemFlags_NoNav                                            8 /* 1 << 3 */
#define ImGuiItemFlags_NoNavDefaultFocus                               16 /* 1 << 4 */
#define ImGuiItemFlags_SelectableDontClosePopup                        32 /* 1 << 5 */
#define ImGuiItemFlags_MixedValue                                      64 /* 1 << 6 */
#define ImGuiItemFlags_ReadOnly                                       128 /* 1 << 7 */
#define ImGuiItemFlags_Inputable                                      256 /* 1 << 8 */
#define ImGuiItemStatusFlags_None                                       0 /* 0 */
#define ImGuiItemStatusFlags_HoveredRect                                1 /* 1 << 0 */
#define ImGuiItemStatusFlags_HasDisplayRect                             2 /* 1 << 1 */
#define ImGuiItemStatusFlags_Edited                                     4 /* 1 << 2 */
#define ImGuiItemStatusFlags_ToggledSelection                           8 /* 1 << 3 */
#define ImGuiItemStatusFlags_ToggledOpen                               16 /* 1 << 4 */
#define ImGuiItemStatusFlags_HasDeactivated                            32 /* 1 << 5 */
#define ImGuiItemStatusFlags_Deactivated                               64 /* 1 << 6 */
#define ImGuiItemStatusFlags_HoveredWindow                            128 /* 1 << 7 */
#define ImGuiItemStatusFlags_FocusedByTabbing                         256 /* 1 << 8 */
#define ImGuiKeyModFlags_None                                           0 /* 0 */
#define ImGuiKeyModFlags_Ctrl                                           1 /* 1 << 0 */
#define ImGuiKeyModFlags_Shift                                          2 /* 1 << 1 */
#define ImGuiKeyModFlags_Alt                                            4 /* 1 << 2 */
#define ImGuiKeyModFlags_Super                                          8 /* 1 << 3 */
#define ImGuiKey_Tab                                                    0 /* 0 */
#define ImGuiKey_LeftArrow                                              1 /* 1 */
#define ImGuiKey_RightArrow                                             2 /* 2 */
#define ImGuiKey_UpArrow                                                3 /* 3 */
#define ImGuiKey_DownArrow                                              4 /* 4 */
#define ImGuiKey_PageUp                                                 5 /* 5 */
#define ImGuiKey_PageDown                                               6 /* 6 */
#define ImGuiKey_Home                                                   7 /* 7 */
#define ImGuiKey_End                                                    8 /* 8 */
#define ImGuiKey_Insert                                                 9 /* 9 */
#define ImGuiKey_Delete                                                10 /* 10 */
#define ImGuiKey_Backspace                                             11 /* 11 */
#define ImGuiKey_Space                                                 12 /* 12 */
#define ImGuiKey_Enter                                                 13 /* 13 */
#define ImGuiKey_Escape                                                14 /* 14 */
#define ImGuiKey_KeyPadEnter                                           15 /* 15 */
#define ImGuiKey_A                                                     16 /* 16 */
#define ImGuiKey_C                                                     17 /* 17 */
#define ImGuiKey_V                                                     18 /* 18 */
#define ImGuiKey_X                                                     19 /* 19 */
#define ImGuiKey_Y                                                     20 /* 20 */
#define ImGuiKey_Z                                                     21 /* 21 */
#define ImGuiKey_COUNT                                                 22 /* 22 */
#define ImGuiLayoutType_Horizontal                                      0 /* 0 */
#define ImGuiLayoutType_Vertical                                        1 /* 1 */
#define ImGuiLogType_None                                               0 /* 0 */
#define ImGuiLogType_TTY                                                1 /* 1 */
#define ImGuiLogType_File                                               2 /* 2 */
#define ImGuiLogType_Buffer                                             3 /* 3 */
#define ImGuiLogType_Clipboard                                          4 /* 4 */
#define ImGuiMouseButton_Left                                           0 /* 0 */
#define ImGuiMouseButton_Right                                          1 /* 1 */
#define ImGuiMouseButton_Middle                                         2 /* 2 */
#define ImGuiMouseButton_COUNT                                          5 /* 5 */
#define ImGuiMouseCursor_None                                          -1 /* -1 */
#define ImGuiMouseCursor_Arrow                                          0 /* 0 */
#define ImGuiMouseCursor_TextInput                                      1 /* 1 */
#define ImGuiMouseCursor_ResizeAll                                      2 /* 2 */
#define ImGuiMouseCursor_ResizeNS                                       3 /* 3 */
#define ImGuiMouseCursor_ResizeEW                                       4 /* 4 */
#define ImGuiMouseCursor_ResizeNESW                                     5 /* 5 */
#define ImGuiMouseCursor_ResizeNWSE                                     6 /* 6 */
#define ImGuiMouseCursor_Hand                                           7 /* 7 */
#define ImGuiMouseCursor_NotAllowed                                     8 /* 8 */
#define ImGuiMouseCursor_COUNT                                          9 /* 9 */
#define ImGuiNavDirSourceFlags_None                                     0 /* 0 */
#define ImGuiNavDirSourceFlags_RawKeyboard                              1 /* 1 << 0 */
#define ImGuiNavDirSourceFlags_Keyboard                                 2 /* 1 << 1 */
#define ImGuiNavDirSourceFlags_PadDPad                                  4 /* 1 << 2 */
#define ImGuiNavDirSourceFlags_PadLStick                                8 /* 1 << 3 */
#define ImGuiNavHighlightFlags_None                                     0 /* 0 */
#define ImGuiNavHighlightFlags_TypeDefault                              1 /* 1 << 0 */
#define ImGuiNavHighlightFlags_TypeThin                                 2 /* 1 << 1 */
#define ImGuiNavHighlightFlags_AlwaysDraw                               4 /* 1 << 2 */
#define ImGuiNavHighlightFlags_NoRounding                               8 /* 1 << 3 */
#define ImGuiNavInput_Activate                                          0 /* 0 */
#define ImGuiNavInput_Cancel                                            1 /* 1 */
#define ImGuiNavInput_Input                                             2 /* 2 */
#define ImGuiNavInput_Menu                                              3 /* 3 */
#define ImGuiNavInput_DpadLeft                                          4 /* 4 */
#define ImGuiNavInput_DpadRight                                         5 /* 5 */
#define ImGuiNavInput_DpadUp                                            6 /* 6 */
#define ImGuiNavInput_DpadDown                                          7 /* 7 */
#define ImGuiNavInput_LStickLeft                                        8 /* 8 */
#define ImGuiNavInput_LStickRight                                       9 /* 9 */
#define ImGuiNavInput_LStickUp                                         10 /* 10 */
#define ImGuiNavInput_LStickDown                                       11 /* 11 */
#define ImGuiNavInput_FocusPrev                                        12 /* 12 */
#define ImGuiNavInput_FocusNext                                        13 /* 13 */
#define ImGuiNavInput_TweakSlow                                        14 /* 14 */
#define ImGuiNavInput_TweakFast                                        15 /* 15 */
#define ImGuiNavInput_KeyLeft_                                         16 /* 16 */
#define ImGuiNavInput_KeyRight_                                        17 /* 17 */
#define ImGuiNavInput_KeyUp_                                           18 /* 18 */
#define ImGuiNavInput_KeyDown_                                         19 /* 19 */
#define ImGuiNavInput_COUNT                                            20 /* 20 */
#define ImGuiNavInput_InternalStart_                                   16 /* ImGuiNavInput_KeyLeft_ */
#define ImGuiNavLayer_Main                                              0 /* 0 */
#define ImGuiNavLayer_Menu                                              1 /* 1 */
#define ImGuiNavLayer_COUNT                                             2 /* 2 */
#define ImGuiNavMoveFlags_None                                          0 /* 0 */
#define ImGuiNavMoveFlags_LoopX                                         1 /* 1 << 0 */
#define ImGuiNavMoveFlags_LoopY                                         2 /* 1 << 1 */
#define ImGuiNavMoveFlags_WrapX                                         4 /* 1 << 2 */
#define ImGuiNavMoveFlags_WrapY                                         8 /* 1 << 3 */
#define ImGuiNavMoveFlags_AllowCurrentNavId                            16 /* 1 << 4 */
#define ImGuiNavMoveFlags_AlsoScoreVisibleSet                          32 /* 1 << 5 */
#define ImGuiNavMoveFlags_ScrollToEdgeY                                64 /* 1 << 6 */
#define ImGuiNavMoveFlags_Forwarded                                   128 /* 1 << 7 */
#define ImGuiNavMoveFlags_DebugNoResult                               256 /* 1 << 8 */
#define ImGuiNavMoveFlags_FocusApi                                    512 /* 1 << 9 */
#define ImGuiNavMoveFlags_Tabbing                                    1024 /* 1 << 10 */
#define ImGuiNavMoveFlags_Activate                                   2048 /* 1 << 11 */
#define ImGuiNavMoveFlags_DontSetNavHighlight                        4096 /* 1 << 12 */
#define ImGuiNextItemDataFlags_None                                     0 /* 0 */
#define ImGuiNextItemDataFlags_HasWidth                                 1 /* 1 << 0 */
#define ImGuiNextItemDataFlags_HasOpen                                  2 /* 1 << 1 */
#define ImGuiNextWindowDataFlags_None                                   0 /* 0 */
#define ImGuiNextWindowDataFlags_HasPos                                 1 /* 1 << 0 */
#define ImGuiNextWindowDataFlags_HasSize                                2 /* 1 << 1 */
#define ImGuiNextWindowDataFlags_HasContentSize                         4 /* 1 << 2 */
#define ImGuiNextWindowDataFlags_HasCollapsed                           8 /* 1 << 3 */
#define ImGuiNextWindowDataFlags_HasSizeConstraint                     16 /* 1 << 4 */
#define ImGuiNextWindowDataFlags_HasFocus                              32 /* 1 << 5 */
#define ImGuiNextWindowDataFlags_HasBgAlpha                            64 /* 1 << 6 */
#define ImGuiNextWindowDataFlags_HasScroll                            128 /* 1 << 7 */
#define ImGuiNextWindowDataFlags_HasViewport                          256 /* 1 << 8 */
#define ImGuiNextWindowDataFlags_HasDock                              512 /* 1 << 9 */
#define ImGuiNextWindowDataFlags_HasWindowClass                      1024 /* 1 << 10 */
#define ImGuiOldColumnFlags_None                                        0 /* 0 */
#define ImGuiOldColumnFlags_NoBorder                                    1 /* 1 << 0 */
#define ImGuiOldColumnFlags_NoResize                                    2 /* 1 << 1 */
#define ImGuiOldColumnFlags_NoPreserveWidths                            4 /* 1 << 2 */
#define ImGuiOldColumnFlags_NoForceWithinWindow                         8 /* 1 << 3 */
#define ImGuiOldColumnFlags_GrowParentContentsSize                     16 /* 1 << 4 */
#define ImGuiPlotType_Lines                                             0 /* 0 */
#define ImGuiPlotType_Histogram                                         1 /* 1 */
#define ImGuiPopupFlags_None                                            0 /* 0 */
#define ImGuiPopupFlags_MouseButtonLeft                                 0 /* 0 */
#define ImGuiPopupFlags_MouseButtonRight                                1 /* 1 */
#define ImGuiPopupFlags_MouseButtonMiddle                               2 /* 2 */
#define ImGuiPopupFlags_MouseButtonMask_                               31 /* 0x1F */
#define ImGuiPopupFlags_MouseButtonDefault_                             1 /* 1 */
#define ImGuiPopupFlags_NoOpenOverExistingPopup                        32 /* 1 << 5 */
#define ImGuiPopupFlags_NoOpenOverItems                                64 /* 1 << 6 */
#define ImGuiPopupFlags_AnyPopupId                                    128 /* 1 << 7 */
#define ImGuiPopupFlags_AnyPopupLevel                                 256 /* 1 << 8 */
#define ImGuiPopupFlags_AnyPopup                                      384 /* ImGuiPopupFlags_AnyPopupId | ImGuiPopupFlags_AnyPopupLevel */
#define ImGuiPopupPositionPolicy_Default                                0 /* 0 */
#define ImGuiPopupPositionPolicy_ComboBox                               1 /* 1 */
#define ImGuiPopupPositionPolicy_Tooltip                                2 /* 2 */
#define ImGuiScrollFlags_None                                           0 /* 0 */
#define ImGuiScrollFlags_KeepVisibleEdgeX                               1 /* 1 << 0 */
#define ImGuiScrollFlags_KeepVisibleEdgeY                               2 /* 1 << 1 */
#define ImGuiScrollFlags_KeepVisibleCenterX                             4 /* 1 << 2 */
#define ImGuiScrollFlags_KeepVisibleCenterY                             8 /* 1 << 3 */
#define ImGuiScrollFlags_AlwaysCenterX                                 16 /* 1 << 4 */
#define ImGuiScrollFlags_AlwaysCenterY                                 32 /* 1 << 5 */
#define ImGuiScrollFlags_NoScrollParent                                64 /* 1 << 6 */
#define ImGuiScrollFlags_MaskX_                                        21 /* ImGuiScrollFlags_KeepVisibleEdgeX | ImGuiScrollFlags_KeepVisibleCenterX | ImGuiScrollFlags_AlwaysCenterX */
#define ImGuiScrollFlags_MaskY_                                        42 /* ImGuiScrollFlags_KeepVisibleEdgeY | ImGuiScrollFlags_KeepVisibleCenterY | ImGuiScrollFlags_AlwaysCenterY */
#define ImGuiSelectableFlags_NoHoldingActiveID                    1048576 /* 1 << 20 */
#define ImGuiSelectableFlags_SelectOnNav                          2097152 /* 1 << 21 */
#define ImGuiSelectableFlags_SelectOnClick                        4194304 /* 1 << 22 */
#define ImGuiSelectableFlags_SelectOnRelease                      8388608 /* 1 << 23 */
#define ImGuiSelectableFlags_SpanAvailWidth                      16777216 /* 1 << 24 */
#define ImGuiSelectableFlags_DrawHoveredWhenHeld                 33554432 /* 1 << 25 */
#define ImGuiSelectableFlags_SetNavIdOnHover                     67108864 /* 1 << 26 */
#define ImGuiSelectableFlags_NoPadWithHalfSpacing               134217728 /* 1 << 27 */
#define ImGuiSelectableFlags_None                                       0 /* 0 */
#define ImGuiSelectableFlags_DontClosePopups                            1 /* 1 << 0 */
#define ImGuiSelectableFlags_SpanAllColumns                             2 /* 1 << 1 */
#define ImGuiSelectableFlags_AllowDoubleClick                           4 /* 1 << 2 */
#define ImGuiSelectableFlags_Disabled                                   8 /* 1 << 3 */
#define ImGuiSelectableFlags_AllowItemOverlap                          16 /* 1 << 4 */
#define ImGuiSeparatorFlags_None                                        0 /* 0 */
#define ImGuiSeparatorFlags_Horizontal                                  1 /* 1 << 0 */
#define ImGuiSeparatorFlags_Vertical                                    2 /* 1 << 1 */
#define ImGuiSeparatorFlags_SpanAllColumns                              4 /* 1 << 2 */
#define ImGuiSliderFlags_Vertical                                 1048576 /* 1 << 20 */
#define ImGuiSliderFlags_ReadOnly                                 2097152 /* 1 << 21 */
#define ImGuiSliderFlags_None                                           0 /* 0 */
#define ImGuiSliderFlags_AlwaysClamp                                   16 /* 1 << 4 */
#define ImGuiSliderFlags_Logarithmic                                   32 /* 1 << 5 */
#define ImGuiSliderFlags_NoRoundToFormat                               64 /* 1 << 6 */
#define ImGuiSliderFlags_NoInput                                      128 /* 1 << 7 */
#define ImGuiSliderFlags_InvalidMask_                           1879048207 /* 0x7000000F */
#define ImGuiSortDirection_None                                         0 /* 0 */
#define ImGuiSortDirection_Ascending                                    1 /* 1 */
#define ImGuiSortDirection_Descending                                   2 /* 2 */
#define ImGuiStyleVar_Alpha                                             0 /* 0 */
#define ImGuiStyleVar_DisabledAlpha                                     1 /* 1 */
#define ImGuiStyleVar_WindowPadding                                     2 /* 2 */
#define ImGuiStyleVar_WindowRounding                                    3 /* 3 */
#define ImGuiStyleVar_WindowBorderSize                                  4 /* 4 */
#define ImGuiStyleVar_WindowMinSize                                     5 /* 5 */
#define ImGuiStyleVar_WindowTitleAlign                                  6 /* 6 */
#define ImGuiStyleVar_ChildRounding                                     7 /* 7 */
#define ImGuiStyleVar_ChildBorderSize                                   8 /* 8 */
#define ImGuiStyleVar_PopupRounding                                     9 /* 9 */
#define ImGuiStyleVar_PopupBorderSize                                  10 /* 10 */
#define ImGuiStyleVar_FramePadding                                     11 /* 11 */
#define ImGuiStyleVar_FrameRounding                                    12 /* 12 */
#define ImGuiStyleVar_FrameBorderSize                                  13 /* 13 */
#define ImGuiStyleVar_ItemSpacing                                      14 /* 14 */
#define ImGuiStyleVar_ItemInnerSpacing                                 15 /* 15 */
#define ImGuiStyleVar_IndentSpacing                                    16 /* 16 */
#define ImGuiStyleVar_CellPadding                                      17 /* 17 */
#define ImGuiStyleVar_ScrollbarSize                                    18 /* 18 */
#define ImGuiStyleVar_ScrollbarRounding                                19 /* 19 */
#define ImGuiStyleVar_GrabMinSize                                      20 /* 20 */
#define ImGuiStyleVar_GrabRounding                                     21 /* 21 */
#define ImGuiStyleVar_TabRounding                                      22 /* 22 */
#define ImGuiStyleVar_ButtonTextAlign                                  23 /* 23 */
#define ImGuiStyleVar_SelectableTextAlign                              24 /* 24 */
#define ImGuiStyleVar_COUNT                                            25 /* 25 */
#define ImGuiTabBarFlags_DockNode                                 1048576 /* 1 << 20 */
#define ImGuiTabBarFlags_IsFocused                                2097152 /* 1 << 21 */
#define ImGuiTabBarFlags_SaveSettings                             4194304 /* 1 << 22 */
#define ImGuiTabBarFlags_None                                           0 /* 0 */
#define ImGuiTabBarFlags_Reorderable                                    1 /* 1 << 0 */
#define ImGuiTabBarFlags_AutoSelectNewTabs                              2 /* 1 << 1 */
#define ImGuiTabBarFlags_TabListPopupButton                             4 /* 1 << 2 */
#define ImGuiTabBarFlags_NoCloseWithMiddleMouseButton                   8 /* 1 << 3 */
#define ImGuiTabBarFlags_NoTabListScrollingButtons                     16 /* 1 << 4 */
#define ImGuiTabBarFlags_NoTooltip                                     32 /* 1 << 5 */
#define ImGuiTabBarFlags_FittingPolicyResizeDown                       64 /* 1 << 6 */
#define ImGuiTabBarFlags_FittingPolicyScroll                          128 /* 1 << 7 */
#define ImGuiTabBarFlags_FittingPolicyMask_                           192 /* ImGuiTabBarFlags_FittingPolicyResizeDown | ImGuiTabBarFlags_FittingPolicyScroll */
#define ImGuiTabBarFlags_FittingPolicyDefault_                         64 /* ImGuiTabBarFlags_FittingPolicyResizeDown */
#define ImGuiTabItemFlags_SectionMask_                                192 /* ImGuiTabItemFlags_Leading | ImGuiTabItemFlags_Trailing */
#define ImGuiTabItemFlags_NoCloseButton                           1048576 /* 1 << 20 */
#define ImGuiTabItemFlags_Button                                  2097152 /* 1 << 21 */
#define ImGuiTabItemFlags_Unsorted                                4194304 /* 1 << 22 */
#define ImGuiTabItemFlags_Preview                                 8388608 /* 1 << 23 */
#define ImGuiTabItemFlags_None                                          0 /* 0 */
#define ImGuiTabItemFlags_UnsavedDocument                               1 /* 1 << 0 */
#define ImGuiTabItemFlags_SetSelected                                   2 /* 1 << 1 */
#define ImGuiTabItemFlags_NoCloseWithMiddleMouseButton                  4 /* 1 << 2 */
#define ImGuiTabItemFlags_NoPushId                                      8 /* 1 << 3 */
#define ImGuiTabItemFlags_NoTooltip                                    16 /* 1 << 4 */
#define ImGuiTabItemFlags_NoReorder                                    32 /* 1 << 5 */
#define ImGuiTabItemFlags_Leading                                      64 /* 1 << 6 */
#define ImGuiTabItemFlags_Trailing                                    128 /* 1 << 7 */
#define ImGuiTableBgTarget_None                                         0 /* 0 */
#define ImGuiTableBgTarget_RowBg0                                       1 /* 1 */
#define ImGuiTableBgTarget_RowBg1                                       2 /* 2 */
#define ImGuiTableBgTarget_CellBg                                       3 /* 3 */
#define ImGuiTableColumnFlags_None                                      0 /* 0 */
#define ImGuiTableColumnFlags_Disabled                                  1 /* 1 << 0 */
#define ImGuiTableColumnFlags_DefaultHide                               2 /* 1 << 1 */
#define ImGuiTableColumnFlags_DefaultSort                               4 /* 1 << 2 */
#define ImGuiTableColumnFlags_WidthStretch                              8 /* 1 << 3 */
#define ImGuiTableColumnFlags_WidthFixed                               16 /* 1 << 4 */
#define ImGuiTableColumnFlags_NoResize                                 32 /* 1 << 5 */
#define ImGuiTableColumnFlags_NoReorder                                64 /* 1 << 6 */
#define ImGuiTableColumnFlags_NoHide                                  128 /* 1 << 7 */
#define ImGuiTableColumnFlags_NoClip                                  256 /* 1 << 8 */
#define ImGuiTableColumnFlags_NoSort                                  512 /* 1 << 9 */
#define ImGuiTableColumnFlags_NoSortAscending                        1024 /* 1 << 10 */
#define ImGuiTableColumnFlags_NoSortDescending                       2048 /* 1 << 11 */
#define ImGuiTableColumnFlags_NoHeaderLabel                          4096 /* 1 << 12 */
#define ImGuiTableColumnFlags_NoHeaderWidth                          8192 /* 1 << 13 */
#define ImGuiTableColumnFlags_PreferSortAscending                   16384 /* 1 << 14 */
#define ImGuiTableColumnFlags_PreferSortDescending                  32768 /* 1 << 15 */
#define ImGuiTableColumnFlags_IndentEnable                          65536 /* 1 << 16 */
#define ImGuiTableColumnFlags_IndentDisable                        131072 /* 1 << 17 */
#define ImGuiTableColumnFlags_IsEnabled                          16777216 /* 1 << 24 */
#define ImGuiTableColumnFlags_IsVisible                          33554432 /* 1 << 25 */
#define ImGuiTableColumnFlags_IsSorted                           67108864 /* 1 << 26 */
#define ImGuiTableColumnFlags_IsHovered                         134217728 /* 1 << 27 */
#define ImGuiTableColumnFlags_WidthMask_                               24 /* ImGuiTableColumnFlags_WidthStretch | ImGuiTableColumnFlags_WidthFixed */
#define ImGuiTableColumnFlags_IndentMask_                          196608 /* ImGuiTableColumnFlags_IndentEnable | ImGuiTableColumnFlags_IndentDisable */
#define ImGuiTableColumnFlags_StatusMask_                       251658240 /* ImGuiTableColumnFlags_IsEnabled | ImGuiTableColumnFlags_IsVisible | ImGuiTableColumnFlags_IsSorted | ImGuiTableColumnFlags_IsHovered */
#define ImGuiTableColumnFlags_NoDirectResize_                   1073741824 /* 1 << 30 */
#define ImGuiTableFlags_None                                            0 /* 0 */
#define ImGuiTableFlags_Resizable                                       1 /* 1 << 0 */
#define ImGuiTableFlags_Reorderable                                     2 /* 1 << 1 */
#define ImGuiTableFlags_Hideable                                        4 /* 1 << 2 */
#define ImGuiTableFlags_Sortable                                        8 /* 1 << 3 */
#define ImGuiTableFlags_NoSavedSettings                                16 /* 1 << 4 */
#define ImGuiTableFlags_ContextMenuInBody                              32 /* 1 << 5 */
#define ImGuiTableFlags_RowBg                                          64 /* 1 << 6 */
#define ImGuiTableFlags_BordersInnerH                                 128 /* 1 << 7 */
#define ImGuiTableFlags_BordersOuterH                                 256 /* 1 << 8 */
#define ImGuiTableFlags_BordersInnerV                                 512 /* 1 << 9 */
#define ImGuiTableFlags_BordersOuterV                                1024 /* 1 << 10 */
#define ImGuiTableFlags_BordersH                                      384 /* ImGuiTableFlags_BordersInnerH | ImGuiTableFlags_BordersOuterH */
#define ImGuiTableFlags_BordersV                                     1536 /* ImGuiTableFlags_BordersInnerV | ImGuiTableFlags_BordersOuterV */
#define ImGuiTableFlags_BordersInner                                  640 /* ImGuiTableFlags_BordersInnerV | ImGuiTableFlags_BordersInnerH */
#define ImGuiTableFlags_BordersOuter                                 1280 /* ImGuiTableFlags_BordersOuterV | ImGuiTableFlags_BordersOuterH */
#define ImGuiTableFlags_Borders                                      1920 /* ImGuiTableFlags_BordersInner | ImGuiTableFlags_BordersOuter */
#define ImGuiTableFlags_NoBordersInBody                              2048 /* 1 << 11 */
#define ImGuiTableFlags_NoBordersInBodyUntilResize                   4096 /* 1 << 12 */
#define ImGuiTableFlags_SizingFixedFit                               8192 /* 1 << 13 */
#define ImGuiTableFlags_SizingFixedSame                             16384 /* 2 << 13 */
#define ImGuiTableFlags_SizingStretchProp                           24576 /* 3 << 13 */
#define ImGuiTableFlags_SizingStretchSame                           32768 /* 4 << 13 */
#define ImGuiTableFlags_NoHostExtendX                               65536 /* 1 << 16 */
#define ImGuiTableFlags_NoHostExtendY                              131072 /* 1 << 17 */
#define ImGuiTableFlags_NoKeepColumnsVisible                       262144 /* 1 << 18 */
#define ImGuiTableFlags_PreciseWidths                              524288 /* 1 << 19 */
#define ImGuiTableFlags_NoClip                                    1048576 /* 1 << 20 */
#define ImGuiTableFlags_PadOuterX                                 2097152 /* 1 << 21 */
#define ImGuiTableFlags_NoPadOuterX                               4194304 /* 1 << 22 */
#define ImGuiTableFlags_NoPadInnerX                               8388608 /* 1 << 23 */
#define ImGuiTableFlags_ScrollX                                  16777216 /* 1 << 24 */
#define ImGuiTableFlags_ScrollY                                  33554432 /* 1 << 25 */
#define ImGuiTableFlags_SortMulti                                67108864 /* 1 << 26 */
#define ImGuiTableFlags_SortTristate                            134217728 /* 1 << 27 */
#define ImGuiTableFlags_SizingMask_                                 57344 /* ImGuiTableFlags_SizingFixedFit | ImGuiTableFlags_SizingFixedSame | ImGuiTableFlags_SizingStretchProp | ImGuiTableFlags_SizingStretchSame */
#define ImGuiTableRowFlags_None                                         0 /* 0 */
#define ImGuiTableRowFlags_Headers                                      1 /* 1 << 0 */
#define ImGuiTextFlags_None                                             0 /* 0 */
#define ImGuiTextFlags_NoWidthForLargeClippedText                       1 /* 1 << 0 */
#define ImGuiTooltipFlags_None                                          0 /* 0 */
#define ImGuiTooltipFlags_OverridePreviousTooltip                       1 /* 1 << 0 */
#define ImGuiTreeNodeFlags_ClipLabelForTrailingButton             1048576 /* 1 << 20 */
#define ImGuiTreeNodeFlags_None                                         0 /* 0 */
#define ImGuiTreeNodeFlags_Selected                                     1 /* 1 << 0 */
#define ImGuiTreeNodeFlags_Framed                                       2 /* 1 << 1 */
#define ImGuiTreeNodeFlags_AllowItemOverlap                             4 /* 1 << 2 */
#define ImGuiTreeNodeFlags_NoTreePushOnOpen                             8 /* 1 << 3 */
#define ImGuiTreeNodeFlags_NoAutoOpenOnLog                             16 /* 1 << 4 */
#define ImGuiTreeNodeFlags_DefaultOpen                                 32 /* 1 << 5 */
#define ImGuiTreeNodeFlags_OpenOnDoubleClick                           64 /* 1 << 6 */
#define ImGuiTreeNodeFlags_OpenOnArrow                                128 /* 1 << 7 */
#define ImGuiTreeNodeFlags_Leaf                                       256 /* 1 << 8 */
#define ImGuiTreeNodeFlags_Bullet                                     512 /* 1 << 9 */
#define ImGuiTreeNodeFlags_FramePadding                              1024 /* 1 << 10 */
#define ImGuiTreeNodeFlags_SpanAvailWidth                            2048 /* 1 << 11 */
#define ImGuiTreeNodeFlags_SpanFullWidth                             4096 /* 1 << 12 */
#define ImGuiTreeNodeFlags_NavLeftJumpsBackHere                      8192 /* 1 << 13 */
#define ImGuiTreeNodeFlags_CollapsingHeader                            26 /* ImGuiTreeNodeFlags_Framed | ImGuiTreeNodeFlags_NoTreePushOnOpen | ImGuiTreeNodeFlags_NoAutoOpenOnLog */
#define ImGuiViewportFlags_None                                         0 /* 0 */
#define ImGuiViewportFlags_IsPlatformWindow                             1 /* 1 << 0 */
#define ImGuiViewportFlags_IsPlatformMonitor                            2 /* 1 << 1 */
#define ImGuiViewportFlags_OwnedByApp                                   4 /* 1 << 2 */
#define ImGuiViewportFlags_NoDecoration                                 8 /* 1 << 3 */
#define ImGuiViewportFlags_NoTaskBarIcon                               16 /* 1 << 4 */
#define ImGuiViewportFlags_NoFocusOnAppearing                          32 /* 1 << 5 */
#define ImGuiViewportFlags_NoFocusOnClick                              64 /* 1 << 6 */
#define ImGuiViewportFlags_NoInputs                                   128 /* 1 << 7 */
#define ImGuiViewportFlags_NoRendererClear                            256 /* 1 << 8 */
#define ImGuiViewportFlags_TopMost                                    512 /* 1 << 9 */
#define ImGuiViewportFlags_Minimized                                 1024 /* 1 << 10 */
#define ImGuiViewportFlags_NoAutoMerge                               2048 /* 1 << 11 */
#define ImGuiViewportFlags_CanHostOtherWindows                       4096 /* 1 << 12 */
#define ImGuiWindowDockStyleCol_Text                                    0 /* 0 */
#define ImGuiWindowDockStyleCol_Tab                                     1 /* 1 */
#define ImGuiWindowDockStyleCol_TabHovered                              2 /* 2 */
#define ImGuiWindowDockStyleCol_TabActive                               3 /* 3 */
#define ImGuiWindowDockStyleCol_TabUnfocused                            4 /* 4 */
#define ImGuiWindowDockStyleCol_TabUnfocusedActive                      5 /* 5 */
#define ImGuiWindowDockStyleCol_COUNT                                   6 /* 6 */
#define ImGuiWindowFlags_None                                           0 /* 0 */
#define ImGuiWindowFlags_NoTitleBar                                     1 /* 1 << 0 */
#define ImGuiWindowFlags_NoResize                                       2 /* 1 << 1 */
#define ImGuiWindowFlags_NoMove                                         4 /* 1 << 2 */
#define ImGuiWindowFlags_NoScrollbar                                    8 /* 1 << 3 */
#define ImGuiWindowFlags_NoScrollWithMouse                             16 /* 1 << 4 */
#define ImGuiWindowFlags_NoCollapse                                    32 /* 1 << 5 */
#define ImGuiWindowFlags_AlwaysAutoResize                              64 /* 1 << 6 */
#define ImGuiWindowFlags_NoBackground                                 128 /* 1 << 7 */
#define ImGuiWindowFlags_NoSavedSettings                              256 /* 1 << 8 */
#define ImGuiWindowFlags_NoMouseInputs                                512 /* 1 << 9 */
#define ImGuiWindowFlags_MenuBar                                     1024 /* 1 << 10 */
#define ImGuiWindowFlags_HorizontalScrollbar                         2048 /* 1 << 11 */
#define ImGuiWindowFlags_NoFocusOnAppearing                          4096 /* 1 << 12 */
#define ImGuiWindowFlags_NoBringToFrontOnFocus                       8192 /* 1 << 13 */
#define ImGuiWindowFlags_AlwaysVerticalScrollbar                    16384 /* 1 << 14 */
#define ImGuiWindowFlags_AlwaysHorizontalScrollbar                  32768 /* 1<< 15 */
#define ImGuiWindowFlags_AlwaysUseWindowPadding                     65536 /* 1 << 16 */
#define ImGuiWindowFlags_NoNavInputs                               262144 /* 1 << 18 */
#define ImGuiWindowFlags_NoNavFocus                                524288 /* 1 << 19 */
#define ImGuiWindowFlags_UnsavedDocument                          1048576 /* 1 << 20 */
#define ImGuiWindowFlags_NoDocking                                2097152 /* 1 << 21 */
#define ImGuiWindowFlags_NoNav                                     786432 /* ImGuiWindowFlags_NoNavInputs | ImGuiWindowFlags_NoNavFocus */
#define ImGuiWindowFlags_NoDecoration                                  43 /* ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoCollapse */
#define ImGuiWindowFlags_NoInputs                                  786944 /* ImGuiWindowFlags_NoMouseInputs | ImGuiWindowFlags_NoNavInputs | ImGuiWindowFlags_NoNavFocus */
#define ImGuiWindowFlags_NavFlattened                             8388608 /* 1 << 23 */
#define ImGuiWindowFlags_ChildWindow                             16777216 /* 1 << 24 */
#define ImGuiWindowFlags_Tooltip                                 33554432 /* 1 << 25 */
#define ImGuiWindowFlags_Popup                                   67108864 /* 1 << 26 */
#define ImGuiWindowFlags_Modal                                  134217728 /* 1 << 27 */
#define ImGuiWindowFlags_ChildMenu                              268435456 /* 1 << 28 */
#define ImGuiWindowFlags_DockNodeHost                           536870912 /* 1 << 29 */
