/* This file is automatically generated by generator.prg originated from
   https://github.com/alcz/harbour-cimgui-sokol-starterkit
   based on output/definitions.json from cimgui https://github.com/cimgui/cimgui which is
   based on imgui.h file version "1.86" from Dear ImGui https://github.com/ocornut/imgui */

#define ImGuiPlatformIO_Platform_CreateWindow           1
#define ImGuiPlatformIO_Platform_DestroyWindow          2
#define ImGuiPlatformIO_Platform_ShowWindow             3
#define ImGuiPlatformIO_Platform_SetWindowPos           4
#define ImGuiPlatformIO_Platform_GetWindowPos           5
#define ImGuiPlatformIO_Platform_SetWindowSize          6
#define ImGuiPlatformIO_Platform_GetWindowSize          7
#define ImGuiPlatformIO_Platform_SetWindowFocus         8
#define ImGuiPlatformIO_Platform_GetWindowFocus         9
#define ImGuiPlatformIO_Platform_GetWindowMinimized    10
#define ImGuiPlatformIO_Platform_SetWindowTitle        11
#define ImGuiPlatformIO_Platform_SetWindowAlpha        12
#define ImGuiPlatformIO_Platform_UpdateWindow          13
#define ImGuiPlatformIO_Platform_RenderWindow          14
#define ImGuiPlatformIO_Platform_SwapBuffers           15
#define ImGuiPlatformIO_Platform_GetWindowDpiScale     16
#define ImGuiPlatformIO_Platform_OnChangedViewport     17
#define ImGuiPlatformIO_Platform_SetImeInputPos        18
#define ImGuiPlatformIO_Platform_CreateVkSurface       19
#define ImGuiPlatformIO_Renderer_CreateWindow          20
#define ImGuiPlatformIO_Renderer_DestroyWindow         21
#define ImGuiPlatformIO_Renderer_SetWindowSize         22
#define ImGuiPlatformIO_Renderer_RenderWindow          23
#define ImGuiPlatformIO_Renderer_SwapBuffers           24
#define ImGuiPlatformIO_Monitors                       25
#define ImGuiPlatformIO_Viewports                      26
#xtranslate ImGuiPlatformIO( <p> ):Platform_CreateWindow => ImGuiPlatformIO_Get( <p>, 1 )
#xtranslate ImGuiPlatformIO( <p> ):Platform_DestroyWindow => ImGuiPlatformIO_Get( <p>, 2 )
#xtranslate ImGuiPlatformIO( <p> ):Platform_ShowWindow => ImGuiPlatformIO_Get( <p>, 3 )
#xtranslate ImGuiPlatformIO( <p> ):Platform_SetWindowPos => ImGuiPlatformIO_Get( <p>, 4 )
#xtranslate ImGuiPlatformIO( <p> ):Platform_GetWindowPos => ImGuiPlatformIO_Get( <p>, 5 )
#xtranslate ImGuiPlatformIO( <p> ):Platform_SetWindowSize => ImGuiPlatformIO_Get( <p>, 6 )
#xtranslate ImGuiPlatformIO( <p> ):Platform_GetWindowSize => ImGuiPlatformIO_Get( <p>, 7 )
#xtranslate ImGuiPlatformIO( <p> ):Platform_SetWindowFocus => ImGuiPlatformIO_Get( <p>, 8 )
#xtranslate ImGuiPlatformIO( <p> ):Platform_GetWindowFocus => ImGuiPlatformIO_Get( <p>, 9 )
#xtranslate ImGuiPlatformIO( <p> ):Platform_GetWindowMinimized => ImGuiPlatformIO_Get( <p>, 10 )
#xtranslate ImGuiPlatformIO( <p> ):Platform_SetWindowTitle => ImGuiPlatformIO_Get( <p>, 11 )
#xtranslate ImGuiPlatformIO( <p> ):Platform_SetWindowAlpha => ImGuiPlatformIO_Get( <p>, 12 )
#xtranslate ImGuiPlatformIO( <p> ):Platform_UpdateWindow => ImGuiPlatformIO_Get( <p>, 13 )
#xtranslate ImGuiPlatformIO( <p> ):Platform_RenderWindow => ImGuiPlatformIO_Get( <p>, 14 )
#xtranslate ImGuiPlatformIO( <p> ):Platform_SwapBuffers => ImGuiPlatformIO_Get( <p>, 15 )
#xtranslate ImGuiPlatformIO( <p> ):Platform_GetWindowDpiScale => ImGuiPlatformIO_Get( <p>, 16 )
#xtranslate ImGuiPlatformIO( <p> ):Platform_OnChangedViewport => ImGuiPlatformIO_Get( <p>, 17 )
#xtranslate ImGuiPlatformIO( <p> ):Platform_SetImeInputPos => ImGuiPlatformIO_Get( <p>, 18 )
#xtranslate ImGuiPlatformIO( <p> ):Platform_CreateVkSurface => ImGuiPlatformIO_Get( <p>, 19 )
#xtranslate ImGuiPlatformIO( <p> ):Renderer_CreateWindow => ImGuiPlatformIO_Get( <p>, 20 )
#xtranslate ImGuiPlatformIO( <p> ):Renderer_DestroyWindow => ImGuiPlatformIO_Get( <p>, 21 )
#xtranslate ImGuiPlatformIO( <p> ):Renderer_SetWindowSize => ImGuiPlatformIO_Get( <p>, 22 )
#xtranslate ImGuiPlatformIO( <p> ):Renderer_RenderWindow => ImGuiPlatformIO_Get( <p>, 23 )
#xtranslate ImGuiPlatformIO( <p> ):Renderer_SwapBuffers => ImGuiPlatformIO_Get( <p>, 24 )
#xtranslate ImGuiPlatformIO( <p> ):Monitors => ImGuiPlatformIO_Get( <p>, 25 )
#xtranslate ImGuiPlatformIO( <p> ):Viewports => ImGuiPlatformIO_Get( <p>, 26 )
#xtranslate ImGuiPlatformIO( <p> ):destroy( [ <args,...> ] ) => ImGuiPlatformIO_destroy( <p>[, <args> ] )
