/* This file is automatically generated by generator.prg originated from
   https://github.com/alcz/harbour-cimgui-sokol-starterkit
   based on output/definitions.json from cimgui https://github.com/cimgui/cimgui which is
   based on imgui.h file version "1.86" from Dear ImGui https://github.com/ocornut/imgui */

#define ImGuiContext_Initialized                             1
#define ImGuiContext_FontAtlasOwnedByContext                 2
#define ImGuiContext_IO                                      3
#define ImGuiContext_PlatformIO                              4
#define ImGuiContext_Style                                   5
#define ImGuiContext_ConfigFlagsCurrFrame                    6
#define ImGuiContext_ConfigFlagsLastFrame                    7
#define ImGuiContext_Font                                    8
#define ImGuiContext_FontSize                                9
#define ImGuiContext_FontBaseSize                           10
#define ImGuiContext_DrawListSharedData                     11
#define ImGuiContext_Time                                   12
#define ImGuiContext_FrameCount                             13
#define ImGuiContext_FrameCountEnded                        14
#define ImGuiContext_FrameCountPlatformEnded                15
#define ImGuiContext_FrameCountRendered                     16
#define ImGuiContext_WithinFrameScope                       17
#define ImGuiContext_WithinFrameScopeWithImplicitWindow     18
#define ImGuiContext_WithinEndChild                         19
#define ImGuiContext_GcCompactAll                           20
#define ImGuiContext_TestEngineHookItems                    21
#define ImGuiContext_TestEngine                             22
#define ImGuiContext_Windows                                23
#define ImGuiContext_WindowsFocusOrder                      24
#define ImGuiContext_WindowsTempSortBuffer                  25
#define ImGuiContext_CurrentWindowStack                     26
#define ImGuiContext_WindowsById                            27
#define ImGuiContext_WindowsActiveCount                     28
#define ImGuiContext_WindowsHoverPadding                    29
#define ImGuiContext_CurrentWindow                          30
#define ImGuiContext_HoveredWindow                          31
#define ImGuiContext_HoveredWindowUnderMovingWindow         32
#define ImGuiContext_HoveredDockNode                        33
#define ImGuiContext_MovingWindow                           34
#define ImGuiContext_WheelingWindow                         35
#define ImGuiContext_WheelingWindowRefMousePos              36
#define ImGuiContext_WheelingWindowTimer                    37
#define ImGuiContext_DebugHookIdInfo                        38
#define ImGuiContext_HoveredId                              39
#define ImGuiContext_HoveredIdPreviousFrame                 40
#define ImGuiContext_HoveredIdAllowOverlap                  41
#define ImGuiContext_HoveredIdUsingMouseWheel               42
#define ImGuiContext_HoveredIdPreviousFrameUsingMouseWheel  43
#define ImGuiContext_HoveredIdDisabled                      44
#define ImGuiContext_HoveredIdTimer                         45
#define ImGuiContext_HoveredIdNotActiveTimer                46
#define ImGuiContext_ActiveId                               47
#define ImGuiContext_ActiveIdIsAlive                        48
#define ImGuiContext_ActiveIdTimer                          49
#define ImGuiContext_ActiveIdIsJustActivated                50
#define ImGuiContext_ActiveIdAllowOverlap                   51
#define ImGuiContext_ActiveIdNoClearOnFocusLoss             52
#define ImGuiContext_ActiveIdHasBeenPressedBefore           53
#define ImGuiContext_ActiveIdHasBeenEditedBefore            54
#define ImGuiContext_ActiveIdHasBeenEditedThisFrame         55
#define ImGuiContext_ActiveIdUsingMouseWheel                56
#define ImGuiContext_ActiveIdUsingNavDirMask                57
#define ImGuiContext_ActiveIdUsingNavInputMask              58
#define ImGuiContext_ActiveIdUsingKeyInputMask              59
#define ImGuiContext_ActiveIdClickOffset                    60
#define ImGuiContext_ActiveIdWindow                         61
#define ImGuiContext_ActiveIdSource                         62
#define ImGuiContext_ActiveIdMouseButton                    63
#define ImGuiContext_ActiveIdPreviousFrame                  64
#define ImGuiContext_ActiveIdPreviousFrameIsAlive           65
#define ImGuiContext_ActiveIdPreviousFrameHasBeenEditedBefore 66
#define ImGuiContext_ActiveIdPreviousFrameWindow            67
#define ImGuiContext_LastActiveId                           68
#define ImGuiContext_LastActiveIdTimer                      69
#define ImGuiContext_CurrentItemFlags                       70
#define ImGuiContext_NextItemData                           71
#define ImGuiContext_LastItemData                           72
#define ImGuiContext_NextWindowData                         73
#define ImGuiContext_ColorStack                             74
#define ImGuiContext_StyleVarStack                          75
#define ImGuiContext_FontStack                              76
#define ImGuiContext_FocusScopeStack                        77
#define ImGuiContext_ItemFlagsStack                         78
#define ImGuiContext_GroupStack                             79
#define ImGuiContext_OpenPopupStack                         80
#define ImGuiContext_BeginPopupStack                        81
#define ImGuiContext_BeginMenuCount                         82
#define ImGuiContext_Viewports                              83
#define ImGuiContext_CurrentDpiScale                        84
#define ImGuiContext_CurrentViewport                        85
#define ImGuiContext_MouseViewport                          86
#define ImGuiContext_MouseLastHoveredViewport               87
#define ImGuiContext_PlatformLastFocusedViewportId          88
#define ImGuiContext_FallbackMonitor                        89
#define ImGuiContext_ViewportFrontMostStampCount            90
#define ImGuiContext_NavWindow                              91
#define ImGuiContext_NavId                                  92
#define ImGuiContext_NavFocusScopeId                        93
#define ImGuiContext_NavActivateId                          94
#define ImGuiContext_NavActivateDownId                      95
#define ImGuiContext_NavActivatePressedId                   96
#define ImGuiContext_NavActivateInputId                     97
#define ImGuiContext_NavActivateFlags                       98
#define ImGuiContext_NavJustMovedToId                       99
#define ImGuiContext_NavJustMovedToFocusScopeId            100
#define ImGuiContext_NavJustMovedToKeyMods                 101
#define ImGuiContext_NavNextActivateId                     102
#define ImGuiContext_NavNextActivateFlags                  103
#define ImGuiContext_NavInputSource                        104
#define ImGuiContext_NavLayer                              105
#define ImGuiContext_NavIdIsAlive                          106
#define ImGuiContext_NavMousePosDirty                      107
#define ImGuiContext_NavDisableHighlight                   108
#define ImGuiContext_NavDisableMouseHover                  109
#define ImGuiContext_NavAnyRequest                         110
#define ImGuiContext_NavInitRequest                        111
#define ImGuiContext_NavInitRequestFromMove                112
#define ImGuiContext_NavInitResultId                       113
#define ImGuiContext_NavInitResultRectRel                  114
#define ImGuiContext_NavMoveSubmitted                      115
#define ImGuiContext_NavMoveScoringItems                   116
#define ImGuiContext_NavMoveForwardToNextFrame             117
#define ImGuiContext_NavMoveFlags                          118
#define ImGuiContext_NavMoveScrollFlags                    119
#define ImGuiContext_NavMoveKeyMods                        120
#define ImGuiContext_NavMoveDir                            121
#define ImGuiContext_NavMoveDirForDebug                    122
#define ImGuiContext_NavMoveClipDir                        123
#define ImGuiContext_NavScoringRect                        124
#define ImGuiContext_NavScoringNoClipRect                  125
#define ImGuiContext_NavScoringDebugCount                  126
#define ImGuiContext_NavTabbingDir                         127
#define ImGuiContext_NavTabbingCounter                     128
#define ImGuiContext_NavMoveResultLocal                    129
#define ImGuiContext_NavMoveResultLocalVisible             130
#define ImGuiContext_NavMoveResultOther                    131
#define ImGuiContext_NavTabbingResultFirst                 132
#define ImGuiContext_NavWindowingTarget                    133
#define ImGuiContext_NavWindowingTargetAnim                134
#define ImGuiContext_NavWindowingListWindow                135
#define ImGuiContext_NavWindowingTimer                     136
#define ImGuiContext_NavWindowingHighlightAlpha            137
#define ImGuiContext_NavWindowingToggleLayer               138
#define ImGuiContext_DimBgRatio                            139
#define ImGuiContext_MouseCursor                           140
#define ImGuiContext_DragDropActive                        141
#define ImGuiContext_DragDropWithinSource                  142
#define ImGuiContext_DragDropWithinTarget                  143
#define ImGuiContext_DragDropSourceFlags                   144
#define ImGuiContext_DragDropSourceFrameCount              145
#define ImGuiContext_DragDropMouseButton                   146
#define ImGuiContext_DragDropPayload                       147
#define ImGuiContext_DragDropTargetRect                    148
#define ImGuiContext_DragDropTargetId                      149
#define ImGuiContext_DragDropAcceptFlags                   150
#define ImGuiContext_DragDropAcceptIdCurrRectSurface       151
#define ImGuiContext_DragDropAcceptIdCurr                  152
#define ImGuiContext_DragDropAcceptIdPrev                  153
#define ImGuiContext_DragDropAcceptFrameCount              154
#define ImGuiContext_DragDropHoldJustPressedId             155
#define ImGuiContext_DragDropPayloadBufHeap                156
#define ImGuiContext_DragDropPayloadBufLocal               157
#define ImGuiContext_ClipperTempDataStacked                158
#define ImGuiContext_ClipperTempData                       159
#define ImGuiContext_CurrentTable                          160
#define ImGuiContext_TablesTempDataStacked                 161
#define ImGuiContext_TablesTempData                        162
#define ImGuiContext_Tables                                163
#define ImGuiContext_TablesLastTimeActive                  164
#define ImGuiContext_DrawChannelsTempMergeBuffer           165
#define ImGuiContext_CurrentTabBar                         166
#define ImGuiContext_TabBars                               167
#define ImGuiContext_CurrentTabBarStack                    168
#define ImGuiContext_ShrinkWidthBuffer                     169
#define ImGuiContext_MouseLastValidPos                     170
#define ImGuiContext_InputTextState                        171
#define ImGuiContext_InputTextPasswordFont                 172
#define ImGuiContext_TempInputId                           173
#define ImGuiContext_ColorEditOptions                      174
#define ImGuiContext_ColorEditLastHue                      175
#define ImGuiContext_ColorEditLastSat                      176
#define ImGuiContext_ColorEditLastColor                    177
#define ImGuiContext_ColorPickerRef                        178
#define ImGuiContext_ComboPreviewData                      179
#define ImGuiContext_SliderCurrentAccum                    180
#define ImGuiContext_SliderCurrentAccumDirty               181
#define ImGuiContext_DragCurrentAccumDirty                 182
#define ImGuiContext_DragCurrentAccum                      183
#define ImGuiContext_DragSpeedDefaultRatio                 184
#define ImGuiContext_ScrollbarClickDeltaToGrabCenter       185
#define ImGuiContext_DisabledAlphaBackup                   186
#define ImGuiContext_DisabledStackSize                     187
#define ImGuiContext_TooltipOverrideCount                  188
#define ImGuiContext_TooltipSlowDelay                      189
#define ImGuiContext_ClipboardHandlerData                  190
#define ImGuiContext_MenusIdSubmittedThisFrame             191
#define ImGuiContext_PlatformImePos                        192
#define ImGuiContext_PlatformImeLastPos                    193
#define ImGuiContext_PlatformImePosViewport                194
#define ImGuiContext_PlatformLocaleDecimalPoint            195
#define ImGuiContext_DockContext                           196
#define ImGuiContext_SettingsLoaded                        197
#define ImGuiContext_SettingsDirtyTimer                    198
#define ImGuiContext_SettingsIniData                       199
#define ImGuiContext_SettingsHandlers                      200
#define ImGuiContext_SettingsWindows                       201
#define ImGuiContext_SettingsTables                        202
#define ImGuiContext_Hooks                                 203
#define ImGuiContext_HookIdNext                            204
#define ImGuiContext_LogEnabled                            205
#define ImGuiContext_LogType                               206
#define ImGuiContext_LogFile                               207
#define ImGuiContext_LogBuffer                             208
#define ImGuiContext_LogNextPrefix                         209
#define ImGuiContext_LogNextSuffix                         210
#define ImGuiContext_LogLinePosY                           211
#define ImGuiContext_LogLineFirstItem                      212
#define ImGuiContext_LogDepthRef                           213
#define ImGuiContext_LogDepthToExpand                      214
#define ImGuiContext_LogDepthToExpandDefault               215
#define ImGuiContext_DebugItemPickerActive                 216
#define ImGuiContext_DebugItemPickerBreakId                217
#define ImGuiContext_DebugMetricsConfig                    218
#define ImGuiContext_DebugStackTool                        219
#define ImGuiContext_FramerateSecPerFrame                  220
#define ImGuiContext_FramerateSecPerFrameIdx               221
#define ImGuiContext_FramerateSecPerFrameCount             222
#define ImGuiContext_FramerateSecPerFrameAccum             223
#define ImGuiContext_WantCaptureMouseNextFrame             224
#define ImGuiContext_WantCaptureKeyboardNextFrame          225
#define ImGuiContext_WantTextInputNextFrame                226
#define ImGuiContext_TempBuffer                            227
#xtranslate ImGuiContext( <p> ):Initialized => ImGuiContext_Get( <p>, 1 )
#xtranslate ImGuiContext( <p> ):FontAtlasOwnedByContext => ImGuiContext_Get( <p>, 2 )
#xtranslate ImGuiContext( <p> ):IO => ImGuiContext_Get( <p>, 3 )
#xtranslate ImGuiContext( <p> ):PlatformIO => ImGuiContext_Get( <p>, 4 )
#xtranslate ImGuiContext( <p> ):Style => ImGuiContext_Get( <p>, 5 )
#xtranslate ImGuiContext( <p> ):ConfigFlagsCurrFrame => ImGuiContext_Get( <p>, 6 )
#xtranslate ImGuiContext( <p> ):ConfigFlagsLastFrame => ImGuiContext_Get( <p>, 7 )
#xtranslate ImGuiContext( <p> ):Font => ImGuiContext_Get( <p>, 8 )
#xtranslate ImGuiContext( <p> ):FontSize => ImGuiContext_Get( <p>, 9 )
#xtranslate ImGuiContext( <p> ):FontBaseSize => ImGuiContext_Get( <p>, 10 )
#xtranslate ImGuiContext( <p> ):DrawListSharedData => ImGuiContext_Get( <p>, 11 )
#xtranslate ImGuiContext( <p> ):Time => ImGuiContext_Get( <p>, 12 )
#xtranslate ImGuiContext( <p> ):FrameCount => ImGuiContext_Get( <p>, 13 )
#xtranslate ImGuiContext( <p> ):FrameCountEnded => ImGuiContext_Get( <p>, 14 )
#xtranslate ImGuiContext( <p> ):FrameCountPlatformEnded => ImGuiContext_Get( <p>, 15 )
#xtranslate ImGuiContext( <p> ):FrameCountRendered => ImGuiContext_Get( <p>, 16 )
#xtranslate ImGuiContext( <p> ):WithinFrameScope => ImGuiContext_Get( <p>, 17 )
#xtranslate ImGuiContext( <p> ):WithinFrameScopeWithImplicitWindow => ImGuiContext_Get( <p>, 18 )
#xtranslate ImGuiContext( <p> ):WithinEndChild => ImGuiContext_Get( <p>, 19 )
#xtranslate ImGuiContext( <p> ):GcCompactAll => ImGuiContext_Get( <p>, 20 )
#xtranslate ImGuiContext( <p> ):TestEngineHookItems => ImGuiContext_Get( <p>, 21 )
#xtranslate ImGuiContext( <p> ):TestEngine => ImGuiContext_Get( <p>, 22 )
#xtranslate ImGuiContext( <p> ):Windows => ImGuiContext_Get( <p>, 23 )
#xtranslate ImGuiContext( <p> ):WindowsFocusOrder => ImGuiContext_Get( <p>, 24 )
#xtranslate ImGuiContext( <p> ):WindowsTempSortBuffer => ImGuiContext_Get( <p>, 25 )
#xtranslate ImGuiContext( <p> ):CurrentWindowStack => ImGuiContext_Get( <p>, 26 )
#xtranslate ImGuiContext( <p> ):WindowsById => ImGuiContext_Get( <p>, 27 )
#xtranslate ImGuiContext( <p> ):WindowsActiveCount => ImGuiContext_Get( <p>, 28 )
#xtranslate ImGuiContext( <p> ):WindowsHoverPadding => ImGuiContext_Get( <p>, 29 )
#xtranslate ImGuiContext( <p> ):CurrentWindow => ImGuiContext_Get( <p>, 30 )
#xtranslate ImGuiContext( <p> ):HoveredWindow => ImGuiContext_Get( <p>, 31 )
#xtranslate ImGuiContext( <p> ):HoveredWindowUnderMovingWindow => ImGuiContext_Get( <p>, 32 )
#xtranslate ImGuiContext( <p> ):HoveredDockNode => ImGuiContext_Get( <p>, 33 )
#xtranslate ImGuiContext( <p> ):MovingWindow => ImGuiContext_Get( <p>, 34 )
#xtranslate ImGuiContext( <p> ):WheelingWindow => ImGuiContext_Get( <p>, 35 )
#xtranslate ImGuiContext( <p> ):WheelingWindowRefMousePos => ImGuiContext_Get( <p>, 36 )
#xtranslate ImGuiContext( <p> ):WheelingWindowTimer => ImGuiContext_Get( <p>, 37 )
#xtranslate ImGuiContext( <p> ):DebugHookIdInfo => ImGuiContext_Get( <p>, 38 )
#xtranslate ImGuiContext( <p> ):HoveredId => ImGuiContext_Get( <p>, 39 )
#xtranslate ImGuiContext( <p> ):HoveredIdPreviousFrame => ImGuiContext_Get( <p>, 40 )
#xtranslate ImGuiContext( <p> ):HoveredIdAllowOverlap => ImGuiContext_Get( <p>, 41 )
#xtranslate ImGuiContext( <p> ):HoveredIdUsingMouseWheel => ImGuiContext_Get( <p>, 42 )
#xtranslate ImGuiContext( <p> ):HoveredIdPreviousFrameUsingMouseWheel => ImGuiContext_Get( <p>, 43 )
#xtranslate ImGuiContext( <p> ):HoveredIdDisabled => ImGuiContext_Get( <p>, 44 )
#xtranslate ImGuiContext( <p> ):HoveredIdTimer => ImGuiContext_Get( <p>, 45 )
#xtranslate ImGuiContext( <p> ):HoveredIdNotActiveTimer => ImGuiContext_Get( <p>, 46 )
#xtranslate ImGuiContext( <p> ):ActiveId => ImGuiContext_Get( <p>, 47 )
#xtranslate ImGuiContext( <p> ):ActiveIdIsAlive => ImGuiContext_Get( <p>, 48 )
#xtranslate ImGuiContext( <p> ):ActiveIdTimer => ImGuiContext_Get( <p>, 49 )
#xtranslate ImGuiContext( <p> ):ActiveIdIsJustActivated => ImGuiContext_Get( <p>, 50 )
#xtranslate ImGuiContext( <p> ):ActiveIdAllowOverlap => ImGuiContext_Get( <p>, 51 )
#xtranslate ImGuiContext( <p> ):ActiveIdNoClearOnFocusLoss => ImGuiContext_Get( <p>, 52 )
#xtranslate ImGuiContext( <p> ):ActiveIdHasBeenPressedBefore => ImGuiContext_Get( <p>, 53 )
#xtranslate ImGuiContext( <p> ):ActiveIdHasBeenEditedBefore => ImGuiContext_Get( <p>, 54 )
#xtranslate ImGuiContext( <p> ):ActiveIdHasBeenEditedThisFrame => ImGuiContext_Get( <p>, 55 )
#xtranslate ImGuiContext( <p> ):ActiveIdUsingMouseWheel => ImGuiContext_Get( <p>, 56 )
#xtranslate ImGuiContext( <p> ):ActiveIdUsingNavDirMask => ImGuiContext_Get( <p>, 57 )
#xtranslate ImGuiContext( <p> ):ActiveIdUsingNavInputMask => ImGuiContext_Get( <p>, 58 )
#xtranslate ImGuiContext( <p> ):ActiveIdUsingKeyInputMask => ImGuiContext_Get( <p>, 59 )
#xtranslate ImGuiContext( <p> ):ActiveIdClickOffset => ImGuiContext_Get( <p>, 60 )
#xtranslate ImGuiContext( <p> ):ActiveIdWindow => ImGuiContext_Get( <p>, 61 )
#xtranslate ImGuiContext( <p> ):ActiveIdSource => ImGuiContext_Get( <p>, 62 )
#xtranslate ImGuiContext( <p> ):ActiveIdMouseButton => ImGuiContext_Get( <p>, 63 )
#xtranslate ImGuiContext( <p> ):ActiveIdPreviousFrame => ImGuiContext_Get( <p>, 64 )
#xtranslate ImGuiContext( <p> ):ActiveIdPreviousFrameIsAlive => ImGuiContext_Get( <p>, 65 )
#xtranslate ImGuiContext( <p> ):ActiveIdPreviousFrameHasBeenEditedBefore => ImGuiContext_Get( <p>, 66 )
#xtranslate ImGuiContext( <p> ):ActiveIdPreviousFrameWindow => ImGuiContext_Get( <p>, 67 )
#xtranslate ImGuiContext( <p> ):LastActiveId => ImGuiContext_Get( <p>, 68 )
#xtranslate ImGuiContext( <p> ):LastActiveIdTimer => ImGuiContext_Get( <p>, 69 )
#xtranslate ImGuiContext( <p> ):CurrentItemFlags => ImGuiContext_Get( <p>, 70 )
#xtranslate ImGuiContext( <p> ):NextItemData => ImGuiContext_Get( <p>, 71 )
#xtranslate ImGuiContext( <p> ):LastItemData => ImGuiContext_Get( <p>, 72 )
#xtranslate ImGuiContext( <p> ):NextWindowData => ImGuiContext_Get( <p>, 73 )
#xtranslate ImGuiContext( <p> ):ColorStack => ImGuiContext_Get( <p>, 74 )
#xtranslate ImGuiContext( <p> ):StyleVarStack => ImGuiContext_Get( <p>, 75 )
#xtranslate ImGuiContext( <p> ):FontStack => ImGuiContext_Get( <p>, 76 )
#xtranslate ImGuiContext( <p> ):FocusScopeStack => ImGuiContext_Get( <p>, 77 )
#xtranslate ImGuiContext( <p> ):ItemFlagsStack => ImGuiContext_Get( <p>, 78 )
#xtranslate ImGuiContext( <p> ):GroupStack => ImGuiContext_Get( <p>, 79 )
#xtranslate ImGuiContext( <p> ):OpenPopupStack => ImGuiContext_Get( <p>, 80 )
#xtranslate ImGuiContext( <p> ):BeginPopupStack => ImGuiContext_Get( <p>, 81 )
#xtranslate ImGuiContext( <p> ):BeginMenuCount => ImGuiContext_Get( <p>, 82 )
#xtranslate ImGuiContext( <p> ):Viewports => ImGuiContext_Get( <p>, 83 )
#xtranslate ImGuiContext( <p> ):CurrentDpiScale => ImGuiContext_Get( <p>, 84 )
#xtranslate ImGuiContext( <p> ):CurrentViewport => ImGuiContext_Get( <p>, 85 )
#xtranslate ImGuiContext( <p> ):MouseViewport => ImGuiContext_Get( <p>, 86 )
#xtranslate ImGuiContext( <p> ):MouseLastHoveredViewport => ImGuiContext_Get( <p>, 87 )
#xtranslate ImGuiContext( <p> ):PlatformLastFocusedViewportId => ImGuiContext_Get( <p>, 88 )
#xtranslate ImGuiContext( <p> ):FallbackMonitor => ImGuiContext_Get( <p>, 89 )
#xtranslate ImGuiContext( <p> ):ViewportFrontMostStampCount => ImGuiContext_Get( <p>, 90 )
#xtranslate ImGuiContext( <p> ):NavWindow => ImGuiContext_Get( <p>, 91 )
#xtranslate ImGuiContext( <p> ):NavId => ImGuiContext_Get( <p>, 92 )
#xtranslate ImGuiContext( <p> ):NavFocusScopeId => ImGuiContext_Get( <p>, 93 )
#xtranslate ImGuiContext( <p> ):NavActivateId => ImGuiContext_Get( <p>, 94 )
#xtranslate ImGuiContext( <p> ):NavActivateDownId => ImGuiContext_Get( <p>, 95 )
#xtranslate ImGuiContext( <p> ):NavActivatePressedId => ImGuiContext_Get( <p>, 96 )
#xtranslate ImGuiContext( <p> ):NavActivateInputId => ImGuiContext_Get( <p>, 97 )
#xtranslate ImGuiContext( <p> ):NavActivateFlags => ImGuiContext_Get( <p>, 98 )
#xtranslate ImGuiContext( <p> ):NavJustMovedToId => ImGuiContext_Get( <p>, 99 )
#xtranslate ImGuiContext( <p> ):NavJustMovedToFocusScopeId => ImGuiContext_Get( <p>, 100 )
#xtranslate ImGuiContext( <p> ):NavJustMovedToKeyMods => ImGuiContext_Get( <p>, 101 )
#xtranslate ImGuiContext( <p> ):NavNextActivateId => ImGuiContext_Get( <p>, 102 )
#xtranslate ImGuiContext( <p> ):NavNextActivateFlags => ImGuiContext_Get( <p>, 103 )
#xtranslate ImGuiContext( <p> ):NavInputSource => ImGuiContext_Get( <p>, 104 )
#xtranslate ImGuiContext( <p> ):NavLayer => ImGuiContext_Get( <p>, 105 )
#xtranslate ImGuiContext( <p> ):NavIdIsAlive => ImGuiContext_Get( <p>, 106 )
#xtranslate ImGuiContext( <p> ):NavMousePosDirty => ImGuiContext_Get( <p>, 107 )
#xtranslate ImGuiContext( <p> ):NavDisableHighlight => ImGuiContext_Get( <p>, 108 )
#xtranslate ImGuiContext( <p> ):NavDisableMouseHover => ImGuiContext_Get( <p>, 109 )
#xtranslate ImGuiContext( <p> ):NavAnyRequest => ImGuiContext_Get( <p>, 110 )
#xtranslate ImGuiContext( <p> ):NavInitRequest => ImGuiContext_Get( <p>, 111 )
#xtranslate ImGuiContext( <p> ):NavInitRequestFromMove => ImGuiContext_Get( <p>, 112 )
#xtranslate ImGuiContext( <p> ):NavInitResultId => ImGuiContext_Get( <p>, 113 )
#xtranslate ImGuiContext( <p> ):NavInitResultRectRel => ImGuiContext_Get( <p>, 114 )
#xtranslate ImGuiContext( <p> ):NavMoveSubmitted => ImGuiContext_Get( <p>, 115 )
#xtranslate ImGuiContext( <p> ):NavMoveScoringItems => ImGuiContext_Get( <p>, 116 )
#xtranslate ImGuiContext( <p> ):NavMoveForwardToNextFrame => ImGuiContext_Get( <p>, 117 )
#xtranslate ImGuiContext( <p> ):NavMoveFlags => ImGuiContext_Get( <p>, 118 )
#xtranslate ImGuiContext( <p> ):NavMoveScrollFlags => ImGuiContext_Get( <p>, 119 )
#xtranslate ImGuiContext( <p> ):NavMoveKeyMods => ImGuiContext_Get( <p>, 120 )
#xtranslate ImGuiContext( <p> ):NavMoveDir => ImGuiContext_Get( <p>, 121 )
#xtranslate ImGuiContext( <p> ):NavMoveDirForDebug => ImGuiContext_Get( <p>, 122 )
#xtranslate ImGuiContext( <p> ):NavMoveClipDir => ImGuiContext_Get( <p>, 123 )
#xtranslate ImGuiContext( <p> ):NavScoringRect => ImGuiContext_Get( <p>, 124 )
#xtranslate ImGuiContext( <p> ):NavScoringNoClipRect => ImGuiContext_Get( <p>, 125 )
#xtranslate ImGuiContext( <p> ):NavScoringDebugCount => ImGuiContext_Get( <p>, 126 )
#xtranslate ImGuiContext( <p> ):NavTabbingDir => ImGuiContext_Get( <p>, 127 )
#xtranslate ImGuiContext( <p> ):NavTabbingCounter => ImGuiContext_Get( <p>, 128 )
#xtranslate ImGuiContext( <p> ):NavMoveResultLocal => ImGuiContext_Get( <p>, 129 )
#xtranslate ImGuiContext( <p> ):NavMoveResultLocalVisible => ImGuiContext_Get( <p>, 130 )
#xtranslate ImGuiContext( <p> ):NavMoveResultOther => ImGuiContext_Get( <p>, 131 )
#xtranslate ImGuiContext( <p> ):NavTabbingResultFirst => ImGuiContext_Get( <p>, 132 )
#xtranslate ImGuiContext( <p> ):NavWindowingTarget => ImGuiContext_Get( <p>, 133 )
#xtranslate ImGuiContext( <p> ):NavWindowingTargetAnim => ImGuiContext_Get( <p>, 134 )
#xtranslate ImGuiContext( <p> ):NavWindowingListWindow => ImGuiContext_Get( <p>, 135 )
#xtranslate ImGuiContext( <p> ):NavWindowingTimer => ImGuiContext_Get( <p>, 136 )
#xtranslate ImGuiContext( <p> ):NavWindowingHighlightAlpha => ImGuiContext_Get( <p>, 137 )
#xtranslate ImGuiContext( <p> ):NavWindowingToggleLayer => ImGuiContext_Get( <p>, 138 )
#xtranslate ImGuiContext( <p> ):DimBgRatio => ImGuiContext_Get( <p>, 139 )
#xtranslate ImGuiContext( <p> ):MouseCursor => ImGuiContext_Get( <p>, 140 )
#xtranslate ImGuiContext( <p> ):DragDropActive => ImGuiContext_Get( <p>, 141 )
#xtranslate ImGuiContext( <p> ):DragDropWithinSource => ImGuiContext_Get( <p>, 142 )
#xtranslate ImGuiContext( <p> ):DragDropWithinTarget => ImGuiContext_Get( <p>, 143 )
#xtranslate ImGuiContext( <p> ):DragDropSourceFlags => ImGuiContext_Get( <p>, 144 )
#xtranslate ImGuiContext( <p> ):DragDropSourceFrameCount => ImGuiContext_Get( <p>, 145 )
#xtranslate ImGuiContext( <p> ):DragDropMouseButton => ImGuiContext_Get( <p>, 146 )
#xtranslate ImGuiContext( <p> ):DragDropPayload => ImGuiContext_Get( <p>, 147 )
#xtranslate ImGuiContext( <p> ):DragDropTargetRect => ImGuiContext_Get( <p>, 148 )
#xtranslate ImGuiContext( <p> ):DragDropTargetId => ImGuiContext_Get( <p>, 149 )
#xtranslate ImGuiContext( <p> ):DragDropAcceptFlags => ImGuiContext_Get( <p>, 150 )
#xtranslate ImGuiContext( <p> ):DragDropAcceptIdCurrRectSurface => ImGuiContext_Get( <p>, 151 )
#xtranslate ImGuiContext( <p> ):DragDropAcceptIdCurr => ImGuiContext_Get( <p>, 152 )
#xtranslate ImGuiContext( <p> ):DragDropAcceptIdPrev => ImGuiContext_Get( <p>, 153 )
#xtranslate ImGuiContext( <p> ):DragDropAcceptFrameCount => ImGuiContext_Get( <p>, 154 )
#xtranslate ImGuiContext( <p> ):DragDropHoldJustPressedId => ImGuiContext_Get( <p>, 155 )
#xtranslate ImGuiContext( <p> ):DragDropPayloadBufHeap => ImGuiContext_Get( <p>, 156 )
#xtranslate ImGuiContext( <p> ):DragDropPayloadBufLocal\[ <n> \] => ImGuiContext_Get( <p>, 157, <n> )
#xtranslate ImGuiContext( <p> ):ClipperTempDataStacked => ImGuiContext_Get( <p>, 158 )
#xtranslate ImGuiContext( <p> ):ClipperTempData => ImGuiContext_Get( <p>, 159 )
#xtranslate ImGuiContext( <p> ):CurrentTable => ImGuiContext_Get( <p>, 160 )
#xtranslate ImGuiContext( <p> ):TablesTempDataStacked => ImGuiContext_Get( <p>, 161 )
#xtranslate ImGuiContext( <p> ):TablesTempData => ImGuiContext_Get( <p>, 162 )
#xtranslate ImGuiContext( <p> ):Tables => ImGuiContext_Get( <p>, 163 )
#xtranslate ImGuiContext( <p> ):TablesLastTimeActive => ImGuiContext_Get( <p>, 164 )
#xtranslate ImGuiContext( <p> ):DrawChannelsTempMergeBuffer => ImGuiContext_Get( <p>, 165 )
#xtranslate ImGuiContext( <p> ):CurrentTabBar => ImGuiContext_Get( <p>, 166 )
#xtranslate ImGuiContext( <p> ):TabBars => ImGuiContext_Get( <p>, 167 )
#xtranslate ImGuiContext( <p> ):CurrentTabBarStack => ImGuiContext_Get( <p>, 168 )
#xtranslate ImGuiContext( <p> ):ShrinkWidthBuffer => ImGuiContext_Get( <p>, 169 )
#xtranslate ImGuiContext( <p> ):MouseLastValidPos => ImGuiContext_Get( <p>, 170 )
#xtranslate ImGuiContext( <p> ):InputTextState => ImGuiContext_Get( <p>, 171 )
#xtranslate ImGuiContext( <p> ):InputTextPasswordFont => ImGuiContext_Get( <p>, 172 )
#xtranslate ImGuiContext( <p> ):TempInputId => ImGuiContext_Get( <p>, 173 )
#xtranslate ImGuiContext( <p> ):ColorEditOptions => ImGuiContext_Get( <p>, 174 )
#xtranslate ImGuiContext( <p> ):ColorEditLastHue => ImGuiContext_Get( <p>, 175 )
#xtranslate ImGuiContext( <p> ):ColorEditLastSat => ImGuiContext_Get( <p>, 176 )
#xtranslate ImGuiContext( <p> ):ColorEditLastColor => ImGuiContext_Get( <p>, 177 )
#xtranslate ImGuiContext( <p> ):ColorPickerRef => ImGuiContext_Get( <p>, 178 )
#xtranslate ImGuiContext( <p> ):ComboPreviewData => ImGuiContext_Get( <p>, 179 )
#xtranslate ImGuiContext( <p> ):SliderCurrentAccum => ImGuiContext_Get( <p>, 180 )
#xtranslate ImGuiContext( <p> ):SliderCurrentAccumDirty => ImGuiContext_Get( <p>, 181 )
#xtranslate ImGuiContext( <p> ):DragCurrentAccumDirty => ImGuiContext_Get( <p>, 182 )
#xtranslate ImGuiContext( <p> ):DragCurrentAccum => ImGuiContext_Get( <p>, 183 )
#xtranslate ImGuiContext( <p> ):DragSpeedDefaultRatio => ImGuiContext_Get( <p>, 184 )
#xtranslate ImGuiContext( <p> ):ScrollbarClickDeltaToGrabCenter => ImGuiContext_Get( <p>, 185 )
#xtranslate ImGuiContext( <p> ):DisabledAlphaBackup => ImGuiContext_Get( <p>, 186 )
#xtranslate ImGuiContext( <p> ):DisabledStackSize => ImGuiContext_Get( <p>, 187 )
#xtranslate ImGuiContext( <p> ):TooltipOverrideCount => ImGuiContext_Get( <p>, 188 )
#xtranslate ImGuiContext( <p> ):TooltipSlowDelay => ImGuiContext_Get( <p>, 189 )
#xtranslate ImGuiContext( <p> ):ClipboardHandlerData => ImGuiContext_Get( <p>, 190 )
#xtranslate ImGuiContext( <p> ):MenusIdSubmittedThisFrame => ImGuiContext_Get( <p>, 191 )
#xtranslate ImGuiContext( <p> ):PlatformImePos => ImGuiContext_Get( <p>, 192 )
#xtranslate ImGuiContext( <p> ):PlatformImeLastPos => ImGuiContext_Get( <p>, 193 )
#xtranslate ImGuiContext( <p> ):PlatformImePosViewport => ImGuiContext_Get( <p>, 194 )
#xtranslate ImGuiContext( <p> ):PlatformLocaleDecimalPoint => ImGuiContext_Get( <p>, 195 )
#xtranslate ImGuiContext( <p> ):DockContext => ImGuiContext_Get( <p>, 196 )
#xtranslate ImGuiContext( <p> ):SettingsLoaded => ImGuiContext_Get( <p>, 197 )
#xtranslate ImGuiContext( <p> ):SettingsDirtyTimer => ImGuiContext_Get( <p>, 198 )
#xtranslate ImGuiContext( <p> ):SettingsIniData => ImGuiContext_Get( <p>, 199 )
#xtranslate ImGuiContext( <p> ):SettingsHandlers => ImGuiContext_Get( <p>, 200 )
#xtranslate ImGuiContext( <p> ):SettingsWindows => ImGuiContext_Get( <p>, 201 )
#xtranslate ImGuiContext( <p> ):SettingsTables => ImGuiContext_Get( <p>, 202 )
#xtranslate ImGuiContext( <p> ):Hooks => ImGuiContext_Get( <p>, 203 )
#xtranslate ImGuiContext( <p> ):HookIdNext => ImGuiContext_Get( <p>, 204 )
#xtranslate ImGuiContext( <p> ):LogEnabled => ImGuiContext_Get( <p>, 205 )
#xtranslate ImGuiContext( <p> ):LogType => ImGuiContext_Get( <p>, 206 )
#xtranslate ImGuiContext( <p> ):LogFile => ImGuiContext_Get( <p>, 207 )
#xtranslate ImGuiContext( <p> ):LogBuffer => ImGuiContext_Get( <p>, 208 )
#xtranslate ImGuiContext( <p> ):LogNextPrefix => ImGuiContext_Get( <p>, 209 )
#xtranslate ImGuiContext( <p> ):LogNextSuffix => ImGuiContext_Get( <p>, 210 )
#xtranslate ImGuiContext( <p> ):LogLinePosY => ImGuiContext_Get( <p>, 211 )
#xtranslate ImGuiContext( <p> ):LogLineFirstItem => ImGuiContext_Get( <p>, 212 )
#xtranslate ImGuiContext( <p> ):LogDepthRef => ImGuiContext_Get( <p>, 213 )
#xtranslate ImGuiContext( <p> ):LogDepthToExpand => ImGuiContext_Get( <p>, 214 )
#xtranslate ImGuiContext( <p> ):LogDepthToExpandDefault => ImGuiContext_Get( <p>, 215 )
#xtranslate ImGuiContext( <p> ):DebugItemPickerActive => ImGuiContext_Get( <p>, 216 )
#xtranslate ImGuiContext( <p> ):DebugItemPickerBreakId => ImGuiContext_Get( <p>, 217 )
#xtranslate ImGuiContext( <p> ):DebugMetricsConfig => ImGuiContext_Get( <p>, 218 )
#xtranslate ImGuiContext( <p> ):DebugStackTool => ImGuiContext_Get( <p>, 219 )
#xtranslate ImGuiContext( <p> ):FramerateSecPerFrame\[ <n> \] => ImGuiContext_Get( <p>, 220, <n> )
#xtranslate ImGuiContext( <p> ):FramerateSecPerFrameIdx => ImGuiContext_Get( <p>, 221 )
#xtranslate ImGuiContext( <p> ):FramerateSecPerFrameCount => ImGuiContext_Get( <p>, 222 )
#xtranslate ImGuiContext( <p> ):FramerateSecPerFrameAccum => ImGuiContext_Get( <p>, 223 )
#xtranslate ImGuiContext( <p> ):WantCaptureMouseNextFrame => ImGuiContext_Get( <p>, 224 )
#xtranslate ImGuiContext( <p> ):WantCaptureKeyboardNextFrame => ImGuiContext_Get( <p>, 225 )
#xtranslate ImGuiContext( <p> ):WantTextInputNextFrame => ImGuiContext_Get( <p>, 226 )
#xtranslate ImGuiContext( <p> ):TempBuffer\[ <n> \] => ImGuiContext_Get( <p>, 227, <n> )
#xtranslate ImGuiContext( <p> ):PlatformLocaleDecimalPoint := <v> => ImGuiContext_Set( <p>, 1, <v> )
#xtranslate ImGuiContext( <p> ):destroy( [ <args,...> ] ) => ImGuiContext_destroy( <p>[, <args> ] )
