/* This file is automatically generated by generator.prg originated from
   https://github.com/alcz/harbour-cimgui-sokol-starterkit
   based on output/definitions.json from cimgui https://github.com/cimgui/cimgui which is
   based on imgui.h file version "1.86" from Dear ImGui https://github.com/ocornut/imgui */

#define ImGuiListClipper_DisplayStart                   1
#define ImGuiListClipper_DisplayEnd                     2
#define ImGuiListClipper_ItemsCount                     3
#define ImGuiListClipper_ItemsHeight                    4
#define ImGuiListClipper_StartPosY                      5
#define ImGuiListClipper_TempData                       6
#xtranslate ImGuiListClipper( <p> ):DisplayStart => ImGuiListClipper_Get( <p>, 1 )
#xtranslate ImGuiListClipper( <p> ):DisplayEnd => ImGuiListClipper_Get( <p>, 2 )
#xtranslate ImGuiListClipper( <p> ):ItemsCount => ImGuiListClipper_Get( <p>, 3 )
#xtranslate ImGuiListClipper( <p> ):ItemsHeight => ImGuiListClipper_Get( <p>, 4 )
#xtranslate ImGuiListClipper( <p> ):StartPosY => ImGuiListClipper_Get( <p>, 5 )
#xtranslate ImGuiListClipper( <p> ):TempData => ImGuiListClipper_Get( <p>, 6 )
#define ImGuiIO_ConfigFlags                             1
#define ImGuiIO_BackendFlags                            2
#define ImGuiIO_DisplaySize                             3
#define ImGuiIO_DeltaTime                               4
#define ImGuiIO_IniSavingRate                           5
#define ImGuiIO_IniFilename                             6
#define ImGuiIO_LogFilename                             7
#define ImGuiIO_MouseDoubleClickTime                    8
#define ImGuiIO_MouseDoubleClickMaxDist                 9
#define ImGuiIO_MouseDragThreshold                     10
#define ImGuiIO_KeyMap                                 11
#define ImGuiIO_KeyRepeatDelay                         12
#define ImGuiIO_KeyRepeatRate                          13
#define ImGuiIO_UserData                               14
#define ImGuiIO_Fonts                                  15
#define ImGuiIO_FontGlobalScale                        16
#define ImGuiIO_FontAllowUserScaling                   17
#define ImGuiIO_FontDefault                            18
#define ImGuiIO_DisplayFramebufferScale                19
#define ImGuiIO_ConfigDockingNoSplit                   20
#define ImGuiIO_ConfigDockingWithShift                 21
#define ImGuiIO_ConfigDockingAlwaysTabBar              22
#define ImGuiIO_ConfigDockingTransparentPayload        23
#define ImGuiIO_ConfigViewportsNoAutoMerge             24
#define ImGuiIO_ConfigViewportsNoTaskBarIcon           25
#define ImGuiIO_ConfigViewportsNoDecoration            26
#define ImGuiIO_ConfigViewportsNoDefaultParent         27
#define ImGuiIO_MouseDrawCursor                        28
#define ImGuiIO_ConfigMacOSXBehaviors                  29
#define ImGuiIO_ConfigInputTextCursorBlink             30
#define ImGuiIO_ConfigDragClickToInputText             31
#define ImGuiIO_ConfigWindowsResizeFromEdges           32
#define ImGuiIO_ConfigWindowsMoveFromTitleBarOnly      33
#define ImGuiIO_ConfigMemoryCompactTimer               34
#define ImGuiIO_BackendPlatformName                    35
#define ImGuiIO_BackendRendererName                    36
#define ImGuiIO_BackendPlatformUserData                37
#define ImGuiIO_BackendRendererUserData                38
#define ImGuiIO_BackendLanguageUserData                39
#define ImGuiIO_GetClipboardTextFn                     40
#define ImGuiIO_SetClipboardTextFn                     41
#define ImGuiIO_ClipboardUserData                      42
#define ImGuiIO_MousePos                               43
#define ImGuiIO_MouseDown                              44
#define ImGuiIO_MouseWheel                             45
#define ImGuiIO_MouseWheelH                            46
#define ImGuiIO_MouseHoveredViewport                   47
#define ImGuiIO_KeyCtrl                                48
#define ImGuiIO_KeyShift                               49
#define ImGuiIO_KeyAlt                                 50
#define ImGuiIO_KeySuper                               51
#define ImGuiIO_KeysDown                               52
#define ImGuiIO_NavInputs                              53
#define ImGuiIO_WantCaptureMouse                       54
#define ImGuiIO_WantCaptureKeyboard                    55
#define ImGuiIO_WantTextInput                          56
#define ImGuiIO_WantSetMousePos                        57
#define ImGuiIO_WantSaveIniSettings                    58
#define ImGuiIO_NavActive                              59
#define ImGuiIO_NavVisible                             60
#define ImGuiIO_Framerate                              61
#define ImGuiIO_MetricsRenderVertices                  62
#define ImGuiIO_MetricsRenderIndices                   63
#define ImGuiIO_MetricsRenderWindows                   64
#define ImGuiIO_MetricsActiveWindows                   65
#define ImGuiIO_MetricsActiveAllocations               66
#define ImGuiIO_MouseDelta                             67
#define ImGuiIO_WantCaptureMouseUnlessPopupClose       68
#define ImGuiIO_KeyMods                                69
#define ImGuiIO_KeyModsPrev                            70
#define ImGuiIO_MousePosPrev                           71
#define ImGuiIO_MouseClickedPos                        72
#define ImGuiIO_MouseClickedTime                       73
#define ImGuiIO_MouseClicked                           74
#define ImGuiIO_MouseDoubleClicked                     75
#define ImGuiIO_MouseClickedCount                      76
#define ImGuiIO_MouseClickedLastCount                  77
#define ImGuiIO_MouseReleased                          78
#define ImGuiIO_MouseDownOwned                         79
#define ImGuiIO_MouseDownOwnedUnlessPopupClose         80
#define ImGuiIO_MouseDownDuration                      81
#define ImGuiIO_MouseDownDurationPrev                  82
#define ImGuiIO_MouseDragMaxDistanceAbs                83
#define ImGuiIO_MouseDragMaxDistanceSqr                84
#define ImGuiIO_KeysDownDuration                       85
#define ImGuiIO_KeysDownDurationPrev                   86
#define ImGuiIO_NavInputsDownDuration                  87
#define ImGuiIO_NavInputsDownDurationPrev              88
#define ImGuiIO_PenPressure                            89
#define ImGuiIO_AppFocusLost                           90
#define ImGuiIO_InputQueueSurrogate                    91
#define ImGuiIO_InputQueueCharacters                   92
#xtranslate ImGuiIO( <p> ):ConfigFlags => ImGuiIO_Get( <p>, 1 )
#xtranslate ImGuiIO( <p> ):BackendFlags => ImGuiIO_Get( <p>, 2 )
#xtranslate ImGuiIO( <p> ):DisplaySize => ImGuiIO_Get( <p>, 3 )
#xtranslate ImGuiIO( <p> ):DeltaTime => ImGuiIO_Get( <p>, 4 )
#xtranslate ImGuiIO( <p> ):IniSavingRate => ImGuiIO_Get( <p>, 5 )
#xtranslate ImGuiIO( <p> ):IniFilename => ImGuiIO_Get( <p>, 6 )
#xtranslate ImGuiIO( <p> ):LogFilename => ImGuiIO_Get( <p>, 7 )
#xtranslate ImGuiIO( <p> ):MouseDoubleClickTime => ImGuiIO_Get( <p>, 8 )
#xtranslate ImGuiIO( <p> ):MouseDoubleClickMaxDist => ImGuiIO_Get( <p>, 9 )
#xtranslate ImGuiIO( <p> ):MouseDragThreshold => ImGuiIO_Get( <p>, 10 )
#xtranslate ImGuiIO( <p> ):KeyMap\[ <n> \] => ImGuiIO_Get( <p>, 11, <n> )
#xtranslate ImGuiIO( <p> ):KeyRepeatDelay => ImGuiIO_Get( <p>, 12 )
#xtranslate ImGuiIO( <p> ):KeyRepeatRate => ImGuiIO_Get( <p>, 13 )
#xtranslate ImGuiIO( <p> ):UserData => ImGuiIO_Get( <p>, 14 )
#xtranslate ImGuiIO( <p> ):Fonts => ImGuiIO_Get( <p>, 15 )
#xtranslate ImGuiIO( <p> ):FontGlobalScale => ImGuiIO_Get( <p>, 16 )
#xtranslate ImGuiIO( <p> ):FontAllowUserScaling => ImGuiIO_Get( <p>, 17 )
#xtranslate ImGuiIO( <p> ):FontDefault => ImGuiIO_Get( <p>, 18 )
#xtranslate ImGuiIO( <p> ):DisplayFramebufferScale => ImGuiIO_Get( <p>, 19 )
#xtranslate ImGuiIO( <p> ):ConfigDockingNoSplit => ImGuiIO_Get( <p>, 20 )
#xtranslate ImGuiIO( <p> ):ConfigDockingWithShift => ImGuiIO_Get( <p>, 21 )
#xtranslate ImGuiIO( <p> ):ConfigDockingAlwaysTabBar => ImGuiIO_Get( <p>, 22 )
#xtranslate ImGuiIO( <p> ):ConfigDockingTransparentPayload => ImGuiIO_Get( <p>, 23 )
#xtranslate ImGuiIO( <p> ):ConfigViewportsNoAutoMerge => ImGuiIO_Get( <p>, 24 )
#xtranslate ImGuiIO( <p> ):ConfigViewportsNoTaskBarIcon => ImGuiIO_Get( <p>, 25 )
#xtranslate ImGuiIO( <p> ):ConfigViewportsNoDecoration => ImGuiIO_Get( <p>, 26 )
#xtranslate ImGuiIO( <p> ):ConfigViewportsNoDefaultParent => ImGuiIO_Get( <p>, 27 )
#xtranslate ImGuiIO( <p> ):MouseDrawCursor => ImGuiIO_Get( <p>, 28 )
#xtranslate ImGuiIO( <p> ):ConfigMacOSXBehaviors => ImGuiIO_Get( <p>, 29 )
#xtranslate ImGuiIO( <p> ):ConfigInputTextCursorBlink => ImGuiIO_Get( <p>, 30 )
#xtranslate ImGuiIO( <p> ):ConfigDragClickToInputText => ImGuiIO_Get( <p>, 31 )
#xtranslate ImGuiIO( <p> ):ConfigWindowsResizeFromEdges => ImGuiIO_Get( <p>, 32 )
#xtranslate ImGuiIO( <p> ):ConfigWindowsMoveFromTitleBarOnly => ImGuiIO_Get( <p>, 33 )
#xtranslate ImGuiIO( <p> ):ConfigMemoryCompactTimer => ImGuiIO_Get( <p>, 34 )
#xtranslate ImGuiIO( <p> ):BackendPlatformName => ImGuiIO_Get( <p>, 35 )
#xtranslate ImGuiIO( <p> ):BackendRendererName => ImGuiIO_Get( <p>, 36 )
#xtranslate ImGuiIO( <p> ):BackendPlatformUserData => ImGuiIO_Get( <p>, 37 )
#xtranslate ImGuiIO( <p> ):BackendRendererUserData => ImGuiIO_Get( <p>, 38 )
#xtranslate ImGuiIO( <p> ):BackendLanguageUserData => ImGuiIO_Get( <p>, 39 )
#xtranslate ImGuiIO( <p> ):GetClipboardTextFn => ImGuiIO_Get( <p>, 40 )
#xtranslate ImGuiIO( <p> ):SetClipboardTextFn => ImGuiIO_Get( <p>, 41 )
#xtranslate ImGuiIO( <p> ):ClipboardUserData => ImGuiIO_Get( <p>, 42 )
#xtranslate ImGuiIO( <p> ):MousePos => ImGuiIO_Get( <p>, 43 )
#xtranslate ImGuiIO( <p> ):MouseDown\[ <n> \] => ImGuiIO_Get( <p>, 44, <n> )
#xtranslate ImGuiIO( <p> ):MouseWheel => ImGuiIO_Get( <p>, 45 )
#xtranslate ImGuiIO( <p> ):MouseWheelH => ImGuiIO_Get( <p>, 46 )
#xtranslate ImGuiIO( <p> ):MouseHoveredViewport => ImGuiIO_Get( <p>, 47 )
#xtranslate ImGuiIO( <p> ):KeyCtrl => ImGuiIO_Get( <p>, 48 )
#xtranslate ImGuiIO( <p> ):KeyShift => ImGuiIO_Get( <p>, 49 )
#xtranslate ImGuiIO( <p> ):KeyAlt => ImGuiIO_Get( <p>, 50 )
#xtranslate ImGuiIO( <p> ):KeySuper => ImGuiIO_Get( <p>, 51 )
#xtranslate ImGuiIO( <p> ):KeysDown\[ <n> \] => ImGuiIO_Get( <p>, 52, <n> )
#xtranslate ImGuiIO( <p> ):NavInputs\[ <n> \] => ImGuiIO_Get( <p>, 53, <n> )
#xtranslate ImGuiIO( <p> ):WantCaptureMouse => ImGuiIO_Get( <p>, 54 )
#xtranslate ImGuiIO( <p> ):WantCaptureKeyboard => ImGuiIO_Get( <p>, 55 )
#xtranslate ImGuiIO( <p> ):WantTextInput => ImGuiIO_Get( <p>, 56 )
#xtranslate ImGuiIO( <p> ):WantSetMousePos => ImGuiIO_Get( <p>, 57 )
#xtranslate ImGuiIO( <p> ):WantSaveIniSettings => ImGuiIO_Get( <p>, 58 )
#xtranslate ImGuiIO( <p> ):NavActive => ImGuiIO_Get( <p>, 59 )
#xtranslate ImGuiIO( <p> ):NavVisible => ImGuiIO_Get( <p>, 60 )
#xtranslate ImGuiIO( <p> ):Framerate => ImGuiIO_Get( <p>, 61 )
#xtranslate ImGuiIO( <p> ):MetricsRenderVertices => ImGuiIO_Get( <p>, 62 )
#xtranslate ImGuiIO( <p> ):MetricsRenderIndices => ImGuiIO_Get( <p>, 63 )
#xtranslate ImGuiIO( <p> ):MetricsRenderWindows => ImGuiIO_Get( <p>, 64 )
#xtranslate ImGuiIO( <p> ):MetricsActiveWindows => ImGuiIO_Get( <p>, 65 )
#xtranslate ImGuiIO( <p> ):MetricsActiveAllocations => ImGuiIO_Get( <p>, 66 )
#xtranslate ImGuiIO( <p> ):MouseDelta => ImGuiIO_Get( <p>, 67 )
#xtranslate ImGuiIO( <p> ):WantCaptureMouseUnlessPopupClose => ImGuiIO_Get( <p>, 68 )
#xtranslate ImGuiIO( <p> ):KeyMods => ImGuiIO_Get( <p>, 69 )
#xtranslate ImGuiIO( <p> ):KeyModsPrev => ImGuiIO_Get( <p>, 70 )
#xtranslate ImGuiIO( <p> ):MousePosPrev => ImGuiIO_Get( <p>, 71 )
#xtranslate ImGuiIO( <p> ):MouseClickedPos\[ <n> \] => ImGuiIO_Get( <p>, 72, <n> )
#xtranslate ImGuiIO( <p> ):MouseClickedTime\[ <n> \] => ImGuiIO_Get( <p>, 73, <n> )
#xtranslate ImGuiIO( <p> ):MouseClicked\[ <n> \] => ImGuiIO_Get( <p>, 74, <n> )
#xtranslate ImGuiIO( <p> ):MouseDoubleClicked\[ <n> \] => ImGuiIO_Get( <p>, 75, <n> )
#xtranslate ImGuiIO( <p> ):MouseClickedCount\[ <n> \] => ImGuiIO_Get( <p>, 76, <n> )
#xtranslate ImGuiIO( <p> ):MouseClickedLastCount\[ <n> \] => ImGuiIO_Get( <p>, 77, <n> )
#xtranslate ImGuiIO( <p> ):MouseReleased\[ <n> \] => ImGuiIO_Get( <p>, 78, <n> )
#xtranslate ImGuiIO( <p> ):MouseDownOwned\[ <n> \] => ImGuiIO_Get( <p>, 79, <n> )
#xtranslate ImGuiIO( <p> ):MouseDownOwnedUnlessPopupClose\[ <n> \] => ImGuiIO_Get( <p>, 80, <n> )
#xtranslate ImGuiIO( <p> ):MouseDownDuration\[ <n> \] => ImGuiIO_Get( <p>, 81, <n> )
#xtranslate ImGuiIO( <p> ):MouseDownDurationPrev\[ <n> \] => ImGuiIO_Get( <p>, 82, <n> )
#xtranslate ImGuiIO( <p> ):MouseDragMaxDistanceAbs\[ <n> \] => ImGuiIO_Get( <p>, 83, <n> )
#xtranslate ImGuiIO( <p> ):MouseDragMaxDistanceSqr\[ <n> \] => ImGuiIO_Get( <p>, 84, <n> )
#xtranslate ImGuiIO( <p> ):KeysDownDuration\[ <n> \] => ImGuiIO_Get( <p>, 85, <n> )
#xtranslate ImGuiIO( <p> ):KeysDownDurationPrev\[ <n> \] => ImGuiIO_Get( <p>, 86, <n> )
#xtranslate ImGuiIO( <p> ):NavInputsDownDuration\[ <n> \] => ImGuiIO_Get( <p>, 87, <n> )
#xtranslate ImGuiIO( <p> ):NavInputsDownDurationPrev\[ <n> \] => ImGuiIO_Get( <p>, 88, <n> )
#xtranslate ImGuiIO( <p> ):PenPressure => ImGuiIO_Get( <p>, 89 )
#xtranslate ImGuiIO( <p> ):AppFocusLost => ImGuiIO_Get( <p>, 90 )
#xtranslate ImGuiIO( <p> ):InputQueueSurrogate => ImGuiIO_Get( <p>, 91 )
#xtranslate ImGuiIO( <p> ):InputQueueCharacters => ImGuiIO_Get( <p>, 92 )
#xtranslate ImGuiIO( <p> ):ConfigFlags := <v> => ImGuiIO_Set( <p>, 1, <v> )
#xtranslate ImGuiIO( <p> ):BackendFlags := <v> => ImGuiIO_Set( <p>, 2, <v> )
#xtranslate ImGuiIO( <p> ):DeltaTime := <v> => ImGuiIO_Set( <p>, 3, <v> )
#xtranslate ImGuiIO( <p> ):IniSavingRate := <v> => ImGuiIO_Set( <p>, 4, <v> )
#xtranslate ImGuiIO( <p> ):MouseDoubleClickTime := <v> => ImGuiIO_Set( <p>, 5, <v> )
#xtranslate ImGuiIO( <p> ):MouseDoubleClickMaxDist := <v> => ImGuiIO_Set( <p>, 6, <v> )
#xtranslate ImGuiIO( <p> ):MouseDragThreshold := <v> => ImGuiIO_Set( <p>, 7, <v> )
#xtranslate ImGuiIO( <p> ):KeyMap\[ <n> \] := <v> => ImGuiIO_Set( <p>, 8, <v>, <n> )
#xtranslate ImGuiIO( <p> ):KeyRepeatDelay := <v> => ImGuiIO_Set( <p>, 9, <v> )
#xtranslate ImGuiIO( <p> ):KeyRepeatRate := <v> => ImGuiIO_Set( <p>, 10, <v> )
#xtranslate ImGuiIO( <p> ):FontGlobalScale := <v> => ImGuiIO_Set( <p>, 11, <v> )
#xtranslate ImGuiIO( <p> ):FontAllowUserScaling := <v> => ImGuiIO_Set( <p>, 12, <v> )
#xtranslate ImGuiIO( <p> ):FontDefault := <v> => ImGuiIO_Set( <p>, 13, <v> )
#xtranslate ImGuiIO( <p> ):DisplayFramebufferScale := <v> => ImGuiIO_Set( <p>, 14, <v> )
#xtranslate ImGuiIO( <p> ):ConfigDockingNoSplit := <v> => ImGuiIO_Set( <p>, 15, <v> )
#xtranslate ImGuiIO( <p> ):ConfigDockingAlwaysTabBar := <v> => ImGuiIO_Set( <p>, 16, <v> )
#xtranslate ImGuiIO( <p> ):ConfigDockingTransparentPayload := <v> => ImGuiIO_Set( <p>, 17, <v> )
#xtranslate ImGuiIO( <p> ):ConfigViewportsNoAutoMerge := <v> => ImGuiIO_Set( <p>, 18, <v> )
#xtranslate ImGuiIO( <p> ):ConfigViewportsNoTaskBarIcon := <v> => ImGuiIO_Set( <p>, 19, <v> )
#xtranslate ImGuiIO( <p> ):ConfigViewportsNoDecoration := <v> => ImGuiIO_Set( <p>, 20, <v> )
#xtranslate ImGuiIO( <p> ):ConfigViewportsNoDefaultParent := <v> => ImGuiIO_Set( <p>, 21, <v> )
#xtranslate ImGuiIO( <p> ):MouseDrawCursor := <v> => ImGuiIO_Set( <p>, 22, <v> )
#xtranslate ImGuiIO( <p> ):ConfigMacOSXBehaviors := <v> => ImGuiIO_Set( <p>, 23, <v> )
#xtranslate ImGuiIO( <p> ):ConfigInputTextCursorBlink := <v> => ImGuiIO_Set( <p>, 24, <v> )
#xtranslate ImGuiIO( <p> ):ConfigDragClickToInputText := <v> => ImGuiIO_Set( <p>, 25, <v> )
#xtranslate ImGuiIO( <p> ):ConfigWindowsResizeFromEdges := <v> => ImGuiIO_Set( <p>, 26, <v> )
#xtranslate ImGuiIO( <p> ):ConfigWindowsMoveFromTitleBarOnly := <v> => ImGuiIO_Set( <p>, 27, <v> )
#xtranslate ImGuiIO( <p> ):ConfigMemoryCompactTimer := <v> => ImGuiIO_Set( <p>, 28, <v> )
#define ImGuiStyle_Alpha                                1
#define ImGuiStyle_DisabledAlpha                        2
#define ImGuiStyle_WindowPadding                        3
#define ImGuiStyle_WindowRounding                       4
#define ImGuiStyle_WindowBorderSize                     5
#define ImGuiStyle_WindowMinSize                        6
#define ImGuiStyle_WindowTitleAlign                     7
#define ImGuiStyle_WindowMenuButtonPosition             8
#define ImGuiStyle_ChildRounding                        9
#define ImGuiStyle_ChildBorderSize                     10
#define ImGuiStyle_PopupRounding                       11
#define ImGuiStyle_PopupBorderSize                     12
#define ImGuiStyle_FramePadding                        13
#define ImGuiStyle_FrameRounding                       14
#define ImGuiStyle_FrameBorderSize                     15
#define ImGuiStyle_ItemSpacing                         16
#define ImGuiStyle_ItemInnerSpacing                    17
#define ImGuiStyle_CellPadding                         18
#define ImGuiStyle_TouchExtraPadding                   19
#define ImGuiStyle_IndentSpacing                       20
#define ImGuiStyle_ColumnsMinSpacing                   21
#define ImGuiStyle_ScrollbarSize                       22
#define ImGuiStyle_ScrollbarRounding                   23
#define ImGuiStyle_GrabMinSize                         24
#define ImGuiStyle_GrabRounding                        25
#define ImGuiStyle_LogSliderDeadzone                   26
#define ImGuiStyle_TabRounding                         27
#define ImGuiStyle_TabBorderSize                       28
#define ImGuiStyle_TabMinWidthForCloseButton           29
#define ImGuiStyle_ColorButtonPosition                 30
#define ImGuiStyle_ButtonTextAlign                     31
#define ImGuiStyle_SelectableTextAlign                 32
#define ImGuiStyle_DisplayWindowPadding                33
#define ImGuiStyle_DisplaySafeAreaPadding              34
#define ImGuiStyle_MouseCursorScale                    35
#define ImGuiStyle_AntiAliasedLines                    36
#define ImGuiStyle_AntiAliasedLinesUseTex              37
#define ImGuiStyle_AntiAliasedFill                     38
#define ImGuiStyle_CurveTessellationTol                39
#define ImGuiStyle_CircleTessellationMaxError          40
#define ImGuiStyle_Colors                              41
#xtranslate ImGuiStyle( <p> ):Alpha => ImGuiStyle_Get( <p>, 1 )
#xtranslate ImGuiStyle( <p> ):DisabledAlpha => ImGuiStyle_Get( <p>, 2 )
#xtranslate ImGuiStyle( <p> ):WindowPadding => ImGuiStyle_Get( <p>, 3 )
#xtranslate ImGuiStyle( <p> ):WindowRounding => ImGuiStyle_Get( <p>, 4 )
#xtranslate ImGuiStyle( <p> ):WindowBorderSize => ImGuiStyle_Get( <p>, 5 )
#xtranslate ImGuiStyle( <p> ):WindowMinSize => ImGuiStyle_Get( <p>, 6 )
#xtranslate ImGuiStyle( <p> ):WindowTitleAlign => ImGuiStyle_Get( <p>, 7 )
#xtranslate ImGuiStyle( <p> ):WindowMenuButtonPosition => ImGuiStyle_Get( <p>, 8 )
#xtranslate ImGuiStyle( <p> ):ChildRounding => ImGuiStyle_Get( <p>, 9 )
#xtranslate ImGuiStyle( <p> ):ChildBorderSize => ImGuiStyle_Get( <p>, 10 )
#xtranslate ImGuiStyle( <p> ):PopupRounding => ImGuiStyle_Get( <p>, 11 )
#xtranslate ImGuiStyle( <p> ):PopupBorderSize => ImGuiStyle_Get( <p>, 12 )
#xtranslate ImGuiStyle( <p> ):FramePadding => ImGuiStyle_Get( <p>, 13 )
#xtranslate ImGuiStyle( <p> ):FrameRounding => ImGuiStyle_Get( <p>, 14 )
#xtranslate ImGuiStyle( <p> ):FrameBorderSize => ImGuiStyle_Get( <p>, 15 )
#xtranslate ImGuiStyle( <p> ):ItemSpacing => ImGuiStyle_Get( <p>, 16 )
#xtranslate ImGuiStyle( <p> ):ItemInnerSpacing => ImGuiStyle_Get( <p>, 17 )
#xtranslate ImGuiStyle( <p> ):CellPadding => ImGuiStyle_Get( <p>, 18 )
#xtranslate ImGuiStyle( <p> ):TouchExtraPadding => ImGuiStyle_Get( <p>, 19 )
#xtranslate ImGuiStyle( <p> ):IndentSpacing => ImGuiStyle_Get( <p>, 20 )
#xtranslate ImGuiStyle( <p> ):ColumnsMinSpacing => ImGuiStyle_Get( <p>, 21 )
#xtranslate ImGuiStyle( <p> ):ScrollbarSize => ImGuiStyle_Get( <p>, 22 )
#xtranslate ImGuiStyle( <p> ):ScrollbarRounding => ImGuiStyle_Get( <p>, 23 )
#xtranslate ImGuiStyle( <p> ):GrabMinSize => ImGuiStyle_Get( <p>, 24 )
#xtranslate ImGuiStyle( <p> ):GrabRounding => ImGuiStyle_Get( <p>, 25 )
#xtranslate ImGuiStyle( <p> ):LogSliderDeadzone => ImGuiStyle_Get( <p>, 26 )
#xtranslate ImGuiStyle( <p> ):TabRounding => ImGuiStyle_Get( <p>, 27 )
#xtranslate ImGuiStyle( <p> ):TabBorderSize => ImGuiStyle_Get( <p>, 28 )
#xtranslate ImGuiStyle( <p> ):TabMinWidthForCloseButton => ImGuiStyle_Get( <p>, 29 )
#xtranslate ImGuiStyle( <p> ):ColorButtonPosition => ImGuiStyle_Get( <p>, 30 )
#xtranslate ImGuiStyle( <p> ):ButtonTextAlign => ImGuiStyle_Get( <p>, 31 )
#xtranslate ImGuiStyle( <p> ):SelectableTextAlign => ImGuiStyle_Get( <p>, 32 )
#xtranslate ImGuiStyle( <p> ):DisplayWindowPadding => ImGuiStyle_Get( <p>, 33 )
#xtranslate ImGuiStyle( <p> ):DisplaySafeAreaPadding => ImGuiStyle_Get( <p>, 34 )
#xtranslate ImGuiStyle( <p> ):MouseCursorScale => ImGuiStyle_Get( <p>, 35 )
#xtranslate ImGuiStyle( <p> ):AntiAliasedLines => ImGuiStyle_Get( <p>, 36 )
#xtranslate ImGuiStyle( <p> ):AntiAliasedLinesUseTex => ImGuiStyle_Get( <p>, 37 )
#xtranslate ImGuiStyle( <p> ):AntiAliasedFill => ImGuiStyle_Get( <p>, 38 )
#xtranslate ImGuiStyle( <p> ):CurveTessellationTol => ImGuiStyle_Get( <p>, 39 )
#xtranslate ImGuiStyle( <p> ):CircleTessellationMaxError => ImGuiStyle_Get( <p>, 40 )
#xtranslate ImGuiStyle( <p> ):Colors\[ <n> \] => ImGuiStyle_Get( <p>, 41, <n> )
#xtranslate ImGuiStyle( <p> ):Alpha := <v> => ImGuiStyle_Set( <p>, 1, <v> )
#xtranslate ImGuiStyle( <p> ):DisabledAlpha := <v> => ImGuiStyle_Set( <p>, 2, <v> )
#xtranslate ImGuiStyle( <p> ):WindowPadding := <v> => ImGuiStyle_Set( <p>, 3, <v> )
#xtranslate ImGuiStyle( <p> ):WindowRounding := <v> => ImGuiStyle_Set( <p>, 4, <v> )
#xtranslate ImGuiStyle( <p> ):WindowBorderSize := <v> => ImGuiStyle_Set( <p>, 5, <v> )
#xtranslate ImGuiStyle( <p> ):WindowMinSize := <v> => ImGuiStyle_Set( <p>, 6, <v> )
#xtranslate ImGuiStyle( <p> ):WindowTitleAlign := <v> => ImGuiStyle_Set( <p>, 7, <v> )
#xtranslate ImGuiStyle( <p> ):WindowMenuButtonPosition := <v> => ImGuiStyle_Set( <p>, 8, <v> )
#xtranslate ImGuiStyle( <p> ):ChildRounding := <v> => ImGuiStyle_Set( <p>, 9, <v> )
#xtranslate ImGuiStyle( <p> ):ChildBorderSize := <v> => ImGuiStyle_Set( <p>, 10, <v> )
#xtranslate ImGuiStyle( <p> ):PopupRounding := <v> => ImGuiStyle_Set( <p>, 11, <v> )
#xtranslate ImGuiStyle( <p> ):PopupBorderSize := <v> => ImGuiStyle_Set( <p>, 12, <v> )
#xtranslate ImGuiStyle( <p> ):FramePadding := <v> => ImGuiStyle_Set( <p>, 13, <v> )
#xtranslate ImGuiStyle( <p> ):FrameRounding := <v> => ImGuiStyle_Set( <p>, 14, <v> )
#xtranslate ImGuiStyle( <p> ):FrameBorderSize := <v> => ImGuiStyle_Set( <p>, 15, <v> )
#xtranslate ImGuiStyle( <p> ):ItemSpacing := <v> => ImGuiStyle_Set( <p>, 16, <v> )
#xtranslate ImGuiStyle( <p> ):ItemInnerSpacing := <v> => ImGuiStyle_Set( <p>, 17, <v> )
#xtranslate ImGuiStyle( <p> ):CellPadding := <v> => ImGuiStyle_Set( <p>, 18, <v> )
#xtranslate ImGuiStyle( <p> ):TouchExtraPadding := <v> => ImGuiStyle_Set( <p>, 19, <v> )
#xtranslate ImGuiStyle( <p> ):IndentSpacing := <v> => ImGuiStyle_Set( <p>, 20, <v> )
#xtranslate ImGuiStyle( <p> ):ColumnsMinSpacing := <v> => ImGuiStyle_Set( <p>, 21, <v> )
#xtranslate ImGuiStyle( <p> ):ScrollbarSize := <v> => ImGuiStyle_Set( <p>, 22, <v> )
#xtranslate ImGuiStyle( <p> ):ScrollbarRounding := <v> => ImGuiStyle_Set( <p>, 23, <v> )
#xtranslate ImGuiStyle( <p> ):GrabMinSize := <v> => ImGuiStyle_Set( <p>, 24, <v> )
#xtranslate ImGuiStyle( <p> ):GrabRounding := <v> => ImGuiStyle_Set( <p>, 25, <v> )
#xtranslate ImGuiStyle( <p> ):LogSliderDeadzone := <v> => ImGuiStyle_Set( <p>, 26, <v> )
#xtranslate ImGuiStyle( <p> ):TabRounding := <v> => ImGuiStyle_Set( <p>, 27, <v> )
#xtranslate ImGuiStyle( <p> ):TabBorderSize := <v> => ImGuiStyle_Set( <p>, 28, <v> )
#xtranslate ImGuiStyle( <p> ):TabMinWidthForCloseButton := <v> => ImGuiStyle_Set( <p>, 29, <v> )
#xtranslate ImGuiStyle( <p> ):ColorButtonPosition := <v> => ImGuiStyle_Set( <p>, 30, <v> )
#xtranslate ImGuiStyle( <p> ):ButtonTextAlign := <v> => ImGuiStyle_Set( <p>, 31, <v> )
#xtranslate ImGuiStyle( <p> ):SelectableTextAlign := <v> => ImGuiStyle_Set( <p>, 32, <v> )
#xtranslate ImGuiStyle( <p> ):DisplayWindowPadding := <v> => ImGuiStyle_Set( <p>, 33, <v> )
#xtranslate ImGuiStyle( <p> ):DisplaySafeAreaPadding := <v> => ImGuiStyle_Set( <p>, 34, <v> )
#xtranslate ImGuiStyle( <p> ):MouseCursorScale := <v> => ImGuiStyle_Set( <p>, 35, <v> )
#xtranslate ImGuiStyle( <p> ):AntiAliasedLines := <v> => ImGuiStyle_Set( <p>, 36, <v> )
#xtranslate ImGuiStyle( <p> ):AntiAliasedLinesUseTex := <v> => ImGuiStyle_Set( <p>, 37, <v> )
#xtranslate ImGuiStyle( <p> ):AntiAliasedFill := <v> => ImGuiStyle_Set( <p>, 38, <v> )
#xtranslate ImGuiStyle( <p> ):CurveTessellationTol := <v> => ImGuiStyle_Set( <p>, 39, <v> )
#xtranslate ImGuiStyle( <p> ):CircleTessellationMaxError := <v> => ImGuiStyle_Set( <p>, 40, <v> )
#xtranslate ImGuiStyle( <p> ):Colors\[ <n> \] := <v> => ImGuiStyle_Set( <p>, 41, <v>, <n> )
#define ImGuiViewport_ID                                1
#define ImGuiViewport_Flags                             2
#define ImGuiViewport_Pos                               3
#define ImGuiViewport_Size                              4
#define ImGuiViewport_WorkPos                           5
#define ImGuiViewport_WorkSize                          6
#define ImGuiViewport_DpiScale                          7
#define ImGuiViewport_ParentViewportId                  8
#define ImGuiViewport_DrawData                          9
#define ImGuiViewport_RendererUserData                 10
#define ImGuiViewport_PlatformUserData                 11
#define ImGuiViewport_PlatformHandle                   12
#define ImGuiViewport_PlatformHandleRaw                13
#define ImGuiViewport_PlatformRequestMove              14
#define ImGuiViewport_PlatformRequestResize            15
#define ImGuiViewport_PlatformRequestClose             16
#xtranslate ImGuiViewport( <p> ):ID => ImGuiViewport_Get( <p>, 1 )
#xtranslate ImGuiViewport( <p> ):Flags => ImGuiViewport_Get( <p>, 2 )
#xtranslate ImGuiViewport( <p> ):Pos => ImGuiViewport_Get( <p>, 3 )
#xtranslate ImGuiViewport( <p> ):Size => ImGuiViewport_Get( <p>, 4 )
#xtranslate ImGuiViewport( <p> ):WorkPos => ImGuiViewport_Get( <p>, 5 )
#xtranslate ImGuiViewport( <p> ):WorkSize => ImGuiViewport_Get( <p>, 6 )
#xtranslate ImGuiViewport( <p> ):DpiScale => ImGuiViewport_Get( <p>, 7 )
#xtranslate ImGuiViewport( <p> ):ParentViewportId => ImGuiViewport_Get( <p>, 8 )
#xtranslate ImGuiViewport( <p> ):DrawData => ImGuiViewport_Get( <p>, 9 )
#xtranslate ImGuiViewport( <p> ):RendererUserData => ImGuiViewport_Get( <p>, 10 )
#xtranslate ImGuiViewport( <p> ):PlatformUserData => ImGuiViewport_Get( <p>, 11 )
#xtranslate ImGuiViewport( <p> ):PlatformHandle => ImGuiViewport_Get( <p>, 12 )
#xtranslate ImGuiViewport( <p> ):PlatformHandleRaw => ImGuiViewport_Get( <p>, 13 )
#xtranslate ImGuiViewport( <p> ):PlatformRequestMove => ImGuiViewport_Get( <p>, 14 )
#xtranslate ImGuiViewport( <p> ):PlatformRequestResize => ImGuiViewport_Get( <p>, 15 )
#xtranslate ImGuiViewport( <p> ):PlatformRequestClose => ImGuiViewport_Get( <p>, 16 )
#define ImGuiWindowClass_ClassId                        1
#define ImGuiWindowClass_ParentViewportId               2
#define ImGuiWindowClass_ViewportFlagsOverrideSet       3
#define ImGuiWindowClass_ViewportFlagsOverrideClear     4
#define ImGuiWindowClass_TabItemFlagsOverrideSet        5
#define ImGuiWindowClass_DockNodeFlagsOverrideSet       6
#define ImGuiWindowClass_DockingAlwaysTabBar            7
#define ImGuiWindowClass_DockingAllowUnclassed          8
#xtranslate ImGuiWindowClass( <p> ):ClassId => ImGuiWindowClass_Get( <p>, 1 )
#xtranslate ImGuiWindowClass( <p> ):ParentViewportId => ImGuiWindowClass_Get( <p>, 2 )
#xtranslate ImGuiWindowClass( <p> ):ViewportFlagsOverrideSet => ImGuiWindowClass_Get( <p>, 3 )
#xtranslate ImGuiWindowClass( <p> ):ViewportFlagsOverrideClear => ImGuiWindowClass_Get( <p>, 4 )
#xtranslate ImGuiWindowClass( <p> ):TabItemFlagsOverrideSet => ImGuiWindowClass_Get( <p>, 5 )
#xtranslate ImGuiWindowClass( <p> ):DockNodeFlagsOverrideSet => ImGuiWindowClass_Get( <p>, 6 )
#xtranslate ImGuiWindowClass( <p> ):DockingAlwaysTabBar => ImGuiWindowClass_Get( <p>, 7 )
#xtranslate ImGuiWindowClass( <p> ):DockingAllowUnclassed => ImGuiWindowClass_Get( <p>, 8 )
#xtranslate ImGuiWindowClass( <p> ):ClassId := <v> => ImGuiWindowClass_Set( <p>, 1, <v> )
#xtranslate ImGuiWindowClass( <p> ):ParentViewportId := <v> => ImGuiWindowClass_Set( <p>, 2, <v> )
#xtranslate ImGuiWindowClass( <p> ):ViewportFlagsOverrideSet := <v> => ImGuiWindowClass_Set( <p>, 3, <v> )
#xtranslate ImGuiWindowClass( <p> ):ViewportFlagsOverrideClear := <v> => ImGuiWindowClass_Set( <p>, 4, <v> )
#xtranslate ImGuiWindowClass( <p> ):TabItemFlagsOverrideSet := <v> => ImGuiWindowClass_Set( <p>, 5, <v> )
#xtranslate ImGuiWindowClass( <p> ):DockNodeFlagsOverrideSet := <v> => ImGuiWindowClass_Set( <p>, 6, <v> )
#xtranslate ImGuiWindowClass( <p> ):DockingAlwaysTabBar := <v> => ImGuiWindowClass_Set( <p>, 7, <v> )
#xtranslate ImGuiWindowClass( <p> ):DockingAllowUnclassed := <v> => ImGuiWindowClass_Set( <p>, 8, <v> )
#xtranslate ImGuiIO( <p> ):AddFocusEvent( [ <args,...> ] ) => ImGuiIO_AddFocusEvent( <p>[, <args> ] )
#xtranslate ImGuiIO( <p> ):AddInputCharacter( [ <args,...> ] ) => ImGuiIO_AddInputCharacter( <p>[, <args> ] )
#xtranslate ImGuiIO( <p> ):AddInputCharacterUTF16( [ <args,...> ] ) => ImGuiIO_AddInputCharacterUTF16( <p>[, <args> ] )
#xtranslate ImGuiIO( <p> ):AddInputCharactersUTF8( [ <args,...> ] ) => ImGuiIO_AddInputCharactersUTF8( <p>[, <args> ] )
#xtranslate ImGuiIO( <p> ):ClearInputCharacters( [ <args,...> ] ) => ImGuiIO_ClearInputCharacters( <p>[, <args> ] )
#xtranslate ImGuiIO( <p> ):ClearInputKeys( [ <args,...> ] ) => ImGuiIO_ClearInputKeys( <p>[, <args> ] )
#xtranslate ImGuiIO( <p> ):destroy( [ <args,...> ] ) => ImGuiIO_destroy( <p>[, <args> ] )
#xtranslate ImGuiListClipper( <p> ):Begin( [ <args,...> ] ) => ImGuiListClipper_Begin( <p>[, <args> ] )
#xtranslate ImGuiListClipper( <p> ):End( [ <args,...> ] ) => ImGuiListClipper_End( <p>[, <args> ] )
#xtranslate ImGuiListClipper( <p> ):ForceDisplayRangeByIndices( [ <args,...> ] ) => ImGuiListClipper_ForceDisplayRangeByIndices( <p>[, <args> ] )
#xtranslate ImGuiListClipper( <p> ):IncludeItemsByIndex( [ <args,...> ] ) => ImGuiListClipper_ForceDisplayRangeByIndices( <p>[, <args> ] )
#xtranslate ImGuiListClipper( <p> ):Step( [ <args,...> ] ) => ImGuiListClipper_Step( <p>[, <args> ] )
#xtranslate ImGuiListClipper( <p> ):destroy( [ <args,...> ] ) => ImGuiListClipper_destroy( <p>[, <args> ] )
#xtranslate ImGuiStyle( <p> ):ScaleAllSizes( [ <args,...> ] ) => ImGuiStyle_ScaleAllSizes( <p>[, <args> ] )
#xtranslate ImGuiStyle( <p> ):destroy( [ <args,...> ] ) => ImGuiStyle_destroy( <p>[, <args> ] )
#xtranslate ImGuiViewport( <p> ):destroy( [ <args,...> ] ) => ImGuiViewport_destroy( <p>[, <args> ] )
#xtranslate ImGuiWindowClass( <p> ):destroy( [ <args,...> ] ) => ImGuiWindowClass_destroy( <p>[, <args> ] )
